// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Application is the predicate function for application builders.
type Application func(*sql.Selector)

// Calculation is the predicate function for calculation builders.
type Calculation func(*sql.Selector)

// Heading is the predicate function for heading builders.
type Heading func(*sql.Selector)

// Metadata is the predicate function for metadata builders.
type Metadata func(*sql.Selector)

// Varsity is the predicate function for varsity builders.
type Varsity func(*sql.Selector)
