package msu

import (
	"github.com/trueegorletov/analabit/core"
	"github.com/trueegorletov/analabit/core/source"
	"github.com/trueegorletov/analabit/core/source/msu"
)

var Varsity = source.VarsityDefinition{
	Code:           "msu",
	Name:           "МГУ",
	HeadingSources: sourcesList(),
}

func sourcesList() []source.HeadingSource {
	return []source.HeadingSource{

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_11",
			PrettyName:            "История",
			RegularAnchor:         "11_02_1_01",
			BVIAnchor:             "11_02_1_01_bvi",
			TargetQuotaAnchors:    []string{"11_02_1_03"},
			DedicatedQuotaAnchors: []string{"11_02_1_04_1", "11_02_1_04_2"},
			SpecialQuotaAnchors:   []string{"11_02_1_02"},
			Capacities:            core.Capacities{Regular: 7, TargetQuota: 1, DedicatedQuota: 1, SpecialQuota: 1},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_11",
			PrettyName:            "История искусств",
			RegularAnchor:         "11_02_1_09",
			BVIAnchor:             "11_02_1_09_bvi",
			TargetQuotaAnchors:    []string{},
			DedicatedQuotaAnchors: []string{"11_02_1_12_1", "11_02_1_12_2"},
			SpecialQuotaAnchors:   []string{"11_02_1_10"},
			Capacities:            core.Capacities{Regular: 19, TargetQuota: 0, DedicatedQuota: 3, SpecialQuota: 3},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_11",
			PrettyName:            "История международных отношений",
			RegularAnchor:         "11_02_1_05",
			BVIAnchor:             "11_02_1_05_bvi",
			TargetQuotaAnchors:    []string{"11_02_1_07"},
			DedicatedQuotaAnchors: []string{"11_02_1_08_1", "11_02_1_08_2"},
			SpecialQuotaAnchors:   []string{"11_02_1_06"},
			Capacities:            core.Capacities{Regular: 9, TargetQuota: 2, DedicatedQuota: 2, SpecialQuota: 2},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_31",
			PrettyName:            "Менеджмент",
			RegularAnchor:         "31_02_1_16",
			BVIAnchor:             "",
			TargetQuotaAnchors:    []string{},
			DedicatedQuotaAnchors: []string{},
			SpecialQuotaAnchors:   []string{},
			Capacities:            core.Capacities{Regular: 15, TargetQuota: 1, DedicatedQuota: 2, SpecialQuota: 2},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_31",
			PrettyName:            "Политология",
			RegularAnchor:         "31_02_1_11",
			BVIAnchor:             "31_02_1_11_bvi",
			TargetQuotaAnchors:    []string{"31_02_1_13"},
			DedicatedQuotaAnchors: []string{"31_02_1_14_1", "31_02_1_14_2"},
			SpecialQuotaAnchors:   []string{"31_02_1_12"},
			Capacities:            core.Capacities{Regular: 17, TargetQuota: 5, DedicatedQuota: 7, SpecialQuota: 9},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_31",
			PrettyName:            "Управление персоналом",
			RegularAnchor:         "31_02_1_01",
			BVIAnchor:             "",
			TargetQuotaAnchors:    []string{"31_02_1_03"},
			DedicatedQuotaAnchors: []string{"31_02_1_04_1", "31_02_1_04_2"},
			SpecialQuotaAnchors:   []string{"31_02_1_02"},
			Capacities:            core.Capacities{Regular: 2, TargetQuota: 1, DedicatedQuota: 1, SpecialQuota: 1},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_29",
			PrettyName:            "Продюсерство",
			RegularAnchor:         "29_01_1_01",
			BVIAnchor:             "29_01_1_01_bvi",
			TargetQuotaAnchors:    []string{},
			DedicatedQuotaAnchors: []string{"29_01_1_04_1", "29_01_1_04_2"},
			SpecialQuotaAnchors:   []string{"29_01_1_02"},
			Capacities:            core.Capacities{Regular: 8, TargetQuota: 0, DedicatedQuota: 2, SpecialQuota: 2},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_32",
			PrettyName:            "Менеджмент",
			RegularAnchor:         "32_02_1_01",
			BVIAnchor:             "",
			TargetQuotaAnchors:    []string{},
			DedicatedQuotaAnchors: []string{},
			SpecialQuotaAnchors:   []string{},
			Capacities:            core.Capacities{Regular: 15, TargetQuota: 1, DedicatedQuota: 2, SpecialQuota: 2},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_33",
			PrettyName:            "Международные отношения",
			RegularAnchor:         "33_02_1_01",
			BVIAnchor:             "",
			TargetQuotaAnchors:    []string{"33_02_1_03"},
			DedicatedQuotaAnchors: []string{"33_02_1_04_1", "33_02_1_04_2"},
			SpecialQuotaAnchors:   []string{"33_02_1_02"},
			Capacities:            core.Capacities{Regular: 8, TargetQuota: 3, DedicatedQuota: 2, SpecialQuota: 2},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_08",
			PrettyName:            "Науки о земле",
			RegularAnchor:         "08_02_1_01",
			BVIAnchor:             "08_02_1_01_bvi",
			TargetQuotaAnchors:    []string{"08_02_1_04"},
			DedicatedQuotaAnchors: []string{"08_02_1_03_1", "08_02_1_03_2"},
			SpecialQuotaAnchors:   []string{"08_02_1_02"},
			Capacities:            core.Capacities{Regular: 89, TargetQuota: 20, DedicatedQuota: 19, SpecialQuota: 19},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_08",
			PrettyName:            "Туризм",
			RegularAnchor:         "08_02_1_08",
			BVIAnchor:             "",
			TargetQuotaAnchors:    []string{"08_02_1_10"},
			DedicatedQuotaAnchors: []string{"08_02_1_11_1", "08_02_1_11_2"},
			SpecialQuotaAnchors:   []string{"08_02_1_09"},
			Capacities:            core.Capacities{Regular: 7, TargetQuota: 1, DedicatedQuota: 1, SpecialQuota: 1},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_01",
			PrettyName:            "Математика",
			RegularAnchor:         "01_01_1_01",
			BVIAnchor:             "01_01_1_01_bvi",
			TargetQuotaAnchors:    []string{"01_01_1_03"},
			DedicatedQuotaAnchors: []string{"01_01_1_04_1", "01_01_1_04_2"},
			SpecialQuotaAnchors:   []string{"01_01_1_02"},
			Capacities:            core.Capacities{Regular: 189, TargetQuota: 11, DedicatedQuota: 25, SpecialQuota: 25},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_01",
			PrettyName:            "Механика",
			RegularAnchor:         "01_01_1_05",
			BVIAnchor:             "01_01_1_05_bvi",
			TargetQuotaAnchors:    []string{"01_01_1_19", "01_01_1_20", "01_01_1_07"},
			DedicatedQuotaAnchors: []string{"01_01_1_08_1", "01_01_1_08_2"},
			SpecialQuotaAnchors:   []string{"01_01_1_06"},
			Capacities:            core.Capacities{Regular: 75, TargetQuota: 5, DedicatedQuota: 10, SpecialQuota: 10},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_10",
			PrettyName:            "Лечебное дело",
			RegularAnchor:         "10_04_1_01",
			BVIAnchor:             "10_01_1_01_bvi",
			TargetQuotaAnchors:    []string{"10_01_1_03"},
			DedicatedQuotaAnchors: []string{"10_01_1_04_1", "10_01_1_04_2"},
			SpecialQuotaAnchors:   []string{"10_01_1_02"},
			Capacities:            core.Capacities{Regular: 5, TargetQuota: 41, DedicatedQuota: 6, SpecialQuota: 6},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_10",
			PrettyName:            "Фармация",
			RegularAnchor:         "10_01_1_05",
			BVIAnchor:             "10_01_1_05_bvi",
			TargetQuotaAnchors:    []string{"10_01_1_07"},
			DedicatedQuotaAnchors: []string{"10_01_1_08_1", "10_01_1_08_2"},
			SpecialQuotaAnchors:   []string{"10_01_1_06"},
			Capacities:            core.Capacities{Regular: 13, TargetQuota: 3, DedicatedQuota: 2, SpecialQuota: 2},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_90",
			PrettyName:            "География",
			RegularAnchor:         "90_02_1_06",
			BVIAnchor:             "",
			TargetQuotaAnchors:    []string{},
			DedicatedQuotaAnchors: []string{"90_02_1_09_1", "90_02_1_09_2"},
			SpecialQuotaAnchors:   []string{"90_02_1_07"},
			Capacities:            core.Capacities{Regular: 6, TargetQuota: 0, DedicatedQuota: 1, SpecialQuota: 1},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_90",
			PrettyName:            "Журналистика",
			RegularAnchor:         "90_02_1_26",
			BVIAnchor:             "",
			TargetQuotaAnchors:    []string{"90_02_1_28"},
			DedicatedQuotaAnchors: []string{"90_02_1_29_1", "90_02_1_29_2"},
			SpecialQuotaAnchors:   []string{"90_02_1_27"},
			Capacities:            core.Capacities{Regular: 10, TargetQuota: 1, DedicatedQuota: 2, SpecialQuota: 2},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_90",
			PrettyName:            "История",
			RegularAnchor:         "90_02_1_36",
			BVIAnchor:             "",
			TargetQuotaAnchors:    []string{"90_02_1_38"},
			DedicatedQuotaAnchors: []string{"90_02_1_39_1", "90_02_1_39_2"},
			SpecialQuotaAnchors:   []string{"90_02_1_37"},
			Capacities:            core.Capacities{Regular: 7, TargetQuota: 1, DedicatedQuota: 1, SpecialQuota: 1},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_90",
			PrettyName:            "Прикладная математика и информатика",
			RegularAnchor:         "90_02_1_01",
			BVIAnchor:             "",
			TargetQuotaAnchors:    []string{"90_02_1_03"},
			DedicatedQuotaAnchors: []string{"90_02_1_04_1", "90_02_1_04_2"},
			SpecialQuotaAnchors:   []string{"90_02_1_02"},
			Capacities:            core.Capacities{Regular: 7, TargetQuota: 2, DedicatedQuota: 3, SpecialQuota: 3},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_90",
			PrettyName:            "Психология",
			RegularAnchor:         "90_02_1_11",
			BVIAnchor:             "",
			TargetQuotaAnchors:    []string{"90_02_1_13"},
			DedicatedQuotaAnchors: []string{"90_02_1_14_1", "90_02_1_14_2"},
			SpecialQuotaAnchors:   []string{"90_02_1_12"},
			Capacities:            core.Capacities{Regular: 7, TargetQuota: 1, DedicatedQuota: 1, SpecialQuota: 1},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_90",
			PrettyName:            "Филология",
			RegularAnchor:         "90_02_1_31",
			BVIAnchor:             "",
			TargetQuotaAnchors:    []string{},
			DedicatedQuotaAnchors: []string{"90_02_1_34_1", "90_02_1_34_2"},
			SpecialQuotaAnchors:   []string{"90_02_1_32"},
			Capacities:            core.Capacities{Regular: 8, TargetQuota: 0, DedicatedQuota: 1, SpecialQuota: 1},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_90",
			PrettyName:            "Фундаментальная и прикладная физика",
			RegularAnchor:         "90_01_1_01",
			BVIAnchor:             "",
			TargetQuotaAnchors:    []string{},
			DedicatedQuotaAnchors: []string{"90_01_1_04_1", "90_01_1_04_2"},
			SpecialQuotaAnchors:   []string{"90_01_1_02"},
			Capacities:            core.Capacities{Regular: 279, TargetQuota: 17, DedicatedQuota: 38, SpecialQuota: 38},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_90",
			PrettyName:            "Экономика",
			RegularAnchor:         "90_02_1_16",
			BVIAnchor:             "",
			TargetQuotaAnchors:    []string{"90_02_1_18"},
			DedicatedQuotaAnchors: []string{"90_02_1_19_1", "90_02_1_19_2"},
			SpecialQuotaAnchors:   []string{"90_02_1_17"},
			Capacities:            core.Capacities{Regular: 7, TargetQuota: 1, DedicatedQuota: 1, SpecialQuota: 1},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_05",
			PrettyName:            "Фундаментальная и прикладная биология",
			RegularAnchor:         "05_01_1_01",
			BVIAnchor:             "05_01_1_01_bvi",
			TargetQuotaAnchors:    []string{"05_01_1_03"},
			DedicatedQuotaAnchors: []string{"05_01_1_04_1", "05_01_1_04_2"},
			SpecialQuotaAnchors:   []string{"05_01_1_02"},
			Capacities:            core.Capacities{Regular: 7, TargetQuota: 5, DedicatedQuota: 4, SpecialQuota: 4},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_05",
			PrettyName:            "Экология и природопользование",
			RegularAnchor:         "05_02_1_01",
			BVIAnchor:             "05_02_1_01_bvi",
			TargetQuotaAnchors:    []string{"05_02_1_03"},
			DedicatedQuotaAnchors: []string{"05_02_1_04_1", "05_02_1_04_2"},
			SpecialQuotaAnchors:   []string{"05_02_1_02"},
			Capacities:            core.Capacities{Regular: 10, TargetQuota: 2, DedicatedQuota: 2, SpecialQuota: 2},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_28",
			PrettyName:            "Конфликтология",
			RegularAnchor:         "28_02_1_11",
			BVIAnchor:             "",
			TargetQuotaAnchors:    []string{"28_02_1_13"},
			DedicatedQuotaAnchors: []string{"28_02_1_14_1", "28_02_1_14_2"},
			SpecialQuotaAnchors:   []string{"28_02_1_12"},
			Capacities:            core.Capacities{Regular: 3, TargetQuota: 1, DedicatedQuota: 4, SpecialQuota: 4},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_28",
			PrettyName:            "Политология",
			RegularAnchor:         "28_02_1_01",
			BVIAnchor:             "28_02_1_01_bvi",
			TargetQuotaAnchors:    []string{"28_02_1_03"},
			DedicatedQuotaAnchors: []string{"28_02_1_04_1", "28_02_1_04_2"},
			SpecialQuotaAnchors:   []string{"28_02_1_02"},
			Capacities:            core.Capacities{Regular: 17, TargetQuota: 5, DedicatedQuota: 7, SpecialQuota: 9},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_27",
			PrettyName:            "Менеджмент",
			RegularAnchor:         "27_02_1_06",
			BVIAnchor:             "",
			TargetQuotaAnchors:    []string{},
			DedicatedQuotaAnchors: []string{},
			SpecialQuotaAnchors:   []string{},
			Capacities:            core.Capacities{Regular: 15, TargetQuota: 1, DedicatedQuota: 2, SpecialQuota: 2},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_27",
			PrettyName:            "Социология",
			RegularAnchor:         "27_02_1_01",
			BVIAnchor:             "27_02_1_01_bvi",
			TargetQuotaAnchors:    []string{"27_02_1_03"},
			DedicatedQuotaAnchors: []string{"27_02_1_04_1", "27_02_1_04_2"},
			SpecialQuotaAnchors:   []string{"27_02_1_02"},
			Capacities:            core.Capacities{Regular: 11, TargetQuota: 2, DedicatedQuota: 4, SpecialQuota: 4},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_27",
			PrettyName:            "Управление персоналом",
			RegularAnchor:         "27_02_1_07",
			BVIAnchor:             "",
			TargetQuotaAnchors:    []string{"27_02_1_09"},
			DedicatedQuotaAnchors: []string{"27_02_1_10_1", "27_02_1_10_2"},
			SpecialQuotaAnchors:   []string{"27_02_1_08"},
			Capacities:            core.Capacities{Regular: 2, TargetQuota: 1, DedicatedQuota: 1, SpecialQuota: 1},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_16",
			PrettyName:            "Журналистика",
			RegularAnchor:         "16_02_1_01",
			BVIAnchor:             "16_02_1_01_bvi",
			TargetQuotaAnchors:    []string{"16_02_1_03"},
			DedicatedQuotaAnchors: []string{"16_02_1_04_1", "16_02_1_04_2"},
			SpecialQuotaAnchors:   []string{"16_02_1_02"},
			Capacities:            core.Capacities{Regular: 10, TargetQuota: 1, DedicatedQuota: 2, SpecialQuota: 2},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_16",
			PrettyName:            "Медиакоммуникации",
			RegularAnchor:         "16_02_1_09",
			BVIAnchor:             "16_02_1_09_bvi",
			TargetQuotaAnchors:    []string{"16_02_1_11"},
			DedicatedQuotaAnchors: []string{"16_02_1_12_1", "16_02_1_12_2"},
			SpecialQuotaAnchors:   []string{"16_02_1_10"},
			Capacities:            core.Capacities{Regular: 15, TargetQuota: 10, DedicatedQuota: 20, SpecialQuota: 20},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_16",
			PrettyName:            "Международная журналистика",
			RegularAnchor:         "16_02_1_05",
			BVIAnchor:             "16_02_1_05_bvi",
			TargetQuotaAnchors:    []string{"16_02_1_07"},
			DedicatedQuotaAnchors: []string{"16_02_1_08_1", "16_02_1_08_2"},
			SpecialQuotaAnchors:   []string{"16_02_1_06"},
			Capacities:            core.Capacities{Regular: 17, TargetQuota: 2, DedicatedQuota: 3, SpecialQuota: 3},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_02",
			PrettyName:            "Прикладная математика и информатика",
			RegularAnchor:         "02_02_1_01",
			BVIAnchor:             "02_02_1_01_bvi",
			TargetQuotaAnchors:    []string{"02_02_1_15", "02_02_1_14", "02_02_1_13", "02_02_1_16", "02_02_1_17", "02_02_1_03"},
			DedicatedQuotaAnchors: []string{"02_02_1_04_1", "02_02_1_04_2"},
			SpecialQuotaAnchors:   []string{"02_02_1_02"},
			Capacities:            core.Capacities{Regular: 7, TargetQuota: 2, DedicatedQuota: 3, SpecialQuota: 3},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_07",
			PrettyName:            "Геология",
			RegularAnchor:         "07_02_1_01",
			BVIAnchor:             "07_02_1_01_bvi",
			TargetQuotaAnchors:    []string{"07_02_1_10", "07_02_1_09", "07_02_1_07", "07_02_1_03"},
			DedicatedQuotaAnchors: []string{"07_02_1_04_1", "07_02_1_04_2"},
			SpecialQuotaAnchors:   []string{"07_02_1_02"},
			Capacities:            core.Capacities{Regular: 150, TargetQuota: 10, DedicatedQuota: 20, SpecialQuota: 20},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_03",
			PrettyName:            "Астрономия",
			RegularAnchor:         "03_01_1_05",
			BVIAnchor:             "03_01_1_05_bvi",
			TargetQuotaAnchors:    []string{},
			DedicatedQuotaAnchors: []string{"03_01_1_07_1", "03_01_1_07_2"},
			SpecialQuotaAnchors:   []string{"03_01_1_06"},
			Capacities:            core.Capacities{Regular: 16, TargetQuota: 0, DedicatedQuota: 2, SpecialQuota: 2},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_03",
			PrettyName:            "Фундаментальная и прикладная физика",
			RegularAnchor:         "03_01_1_01",
			BVIAnchor:             "03_01_1_01_bvi",
			TargetQuotaAnchors:    []string{"03_01_1_17", "03_01_1_04"},
			DedicatedQuotaAnchors: []string{"03_01_1_03_1", "03_01_1_03_2"},
			SpecialQuotaAnchors:   []string{"03_01_1_02"},
			Capacities:            core.Capacities{Regular: 279, TargetQuota: 17, DedicatedQuota: 38, SpecialQuota: 38},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_34",
			PrettyName:            "Экономика",
			RegularAnchor:         "34_02_1_01",
			BVIAnchor:             "34_02_1_01_bvi",
			TargetQuotaAnchors:    []string{},
			DedicatedQuotaAnchors: []string{},
			SpecialQuotaAnchors:   []string{},
			Capacities:            core.Capacities{Regular: 7, TargetQuota: 1, DedicatedQuota: 1, SpecialQuota: 1},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_17",
			PrettyName:            "Клиническая психология",
			RegularAnchor:         "17_01_1_01",
			BVIAnchor:             "17_01_1_01_bvi",
			TargetQuotaAnchors:    []string{"17_01_1_03"},
			DedicatedQuotaAnchors: []string{"17_01_1_04_1", "17_01_1_04_2"},
			SpecialQuotaAnchors:   []string{"17_01_1_02"},
			Capacities:            core.Capacities{Regular: 40, TargetQuota: 3, DedicatedQuota: 6, SpecialQuota: 6},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_17",
			PrettyName:            "Педагогика и психология девиантного поведения",
			RegularAnchor:         "17_01_1_09",
			BVIAnchor:             "",
			TargetQuotaAnchors:    []string{"17_01_1_11"},
			DedicatedQuotaAnchors: []string{"17_01_1_12_1", "17_01_1_12_2"},
			SpecialQuotaAnchors:   []string{"17_01_1_10"},
			Capacities:            core.Capacities{Regular: 10, TargetQuota: 4, DedicatedQuota: 2, SpecialQuota: 2},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_17",
			PrettyName:            "Психология служебной деятельности",
			RegularAnchor:         "17_01_1_05",
			BVIAnchor:             "17_01_1_05_bvi",
			TargetQuotaAnchors:    []string{},
			DedicatedQuotaAnchors: []string{"17_01_1_08_1", "17_01_1_08_2"},
			SpecialQuotaAnchors:   []string{"17_01_1_06"},
			Capacities:            core.Capacities{Regular: 8, TargetQuota: 7, DedicatedQuota: 17, SpecialQuota: 17},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_14",
			PrettyName:            "Менеджмент",
			RegularAnchor:         "14_02_1_05",
			BVIAnchor:             "14_02_1_05_bvi",
			TargetQuotaAnchors:    []string{"14_02_1_16", "14_02_1_07"},
			DedicatedQuotaAnchors: []string{"14_02_1_08_1", "14_02_1_08_2"},
			SpecialQuotaAnchors:   []string{"14_02_1_06"},
			Capacities:            core.Capacities{Regular: 15, TargetQuota: 1, DedicatedQuota: 2, SpecialQuota: 2},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_14",
			PrettyName:            "Экономика",
			RegularAnchor:         "14_02_1_01",
			BVIAnchor:             "14_02_1_01_bvi",
			TargetQuotaAnchors:    []string{"14_02_1_15", "14_02_1_13", "14_02_1_14", "14_02_1_03"},
			DedicatedQuotaAnchors: []string{"14_02_1_04_1", "14_02_1_04_2"},
			SpecialQuotaAnchors:   []string{"14_02_1_02"},
			Capacities:            core.Capacities{Regular: 7, TargetQuota: 1, DedicatedQuota: 1, SpecialQuota: 1},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_12",
			PrettyName:            "Зарубежная филология",
			RegularAnchor:         "12_02_1_05",
			BVIAnchor:             "12_02_1_05_bvi",
			TargetQuotaAnchors:    []string{"12_02_1_07"},
			DedicatedQuotaAnchors: []string{"12_02_1_08_1", "12_02_1_08_2"},
			SpecialQuotaAnchors:   []string{"12_02_1_06"},
			Capacities:            core.Capacities{Regular: 41, TargetQuota: 11, DedicatedQuota: 14, SpecialQuota: 14},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_12",
			PrettyName:            "Русский язык и литература",
			RegularAnchor:         "12_02_1_01",
			BVIAnchor:             "12_02_1_01_bvi",
			TargetQuotaAnchors:    []string{"12_02_1_03"},
			DedicatedQuotaAnchors: []string{"12_02_1_04_1", "12_02_1_04_2"},
			SpecialQuotaAnchors:   []string{"12_02_1_02"},
			Capacities:            core.Capacities{Regular: 27, TargetQuota: 16, DedicatedQuota: 16, SpecialQuota: 16},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_39",
			PrettyName:            "Космические исследования и космонавтика",
			RegularAnchor:         "39_01_1_01",
			BVIAnchor:             "39_01_1_01_bvi",
			TargetQuotaAnchors:    []string{"39_01_1_03"},
			DedicatedQuotaAnchors: []string{"39_01_1_04_1", "39_01_1_04_2"},
			SpecialQuotaAnchors:   []string{"39_01_1_02"},
			Capacities:            core.Capacities{Regular: 38, TargetQuota: 2, DedicatedQuota: 5, SpecialQuota: 5},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_18",
			PrettyName:            "Востоковедение и африканистика",
			RegularAnchor:         "18_02_1_01",
			BVIAnchor:             "18_02_1_01_bvi",
			TargetQuotaAnchors:    []string{"18_02_1_07", "18_02_1_03"},
			DedicatedQuotaAnchors: []string{"18_02_1_04_1", "18_02_1_04_2"},
			SpecialQuotaAnchors:   []string{"18_02_1_02"},
			Capacities:            core.Capacities{Regular: 46, TargetQuota: 8, DedicatedQuota: 23, SpecialQuota: 23},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_15",
			PrettyName:            "Юриспруденция",
			RegularAnchor:         "15_02_1_01",
			BVIAnchor:             "15_02_1_01_bvi",
			TargetQuotaAnchors:    []string{"15_02_1_09", "15_02_1_11", "15_02_1_10", "15_02_1_08", "15_02_1_03"},
			DedicatedQuotaAnchors: []string{"15_02_1_04_1", "15_02_1_04_2"},
			SpecialQuotaAnchors:   []string{"15_02_1_02"},
			Capacities:            core.Capacities{Regular: 14, TargetQuota: 2, DedicatedQuota: 2, SpecialQuota: 2},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_13",
			PrettyName:            "Культурология",
			RegularAnchor:         "13_02_1_13",
			BVIAnchor:             "13_02_1_13_bvi",
			TargetQuotaAnchors:    []string{},
			DedicatedQuotaAnchors: []string{"13_02_1_16_1", "13_02_1_16_2"},
			SpecialQuotaAnchors:   []string{"13_02_1_14"},
			Capacities:            core.Capacities{Regular: 5, TargetQuota: 0, DedicatedQuota: 1, SpecialQuota: 1},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_13",
			PrettyName:            "Реклама и связи с общественностью",
			RegularAnchor:         "13_02_1_09",
			BVIAnchor:             "",
			TargetQuotaAnchors:    []string{"13_02_1_11"},
			DedicatedQuotaAnchors: []string{"13_02_1_12_1", "13_02_1_12_2"},
			SpecialQuotaAnchors:   []string{"13_02_1_10"},
			Capacities:            core.Capacities{Regular: 10, TargetQuota: 1, DedicatedQuota: 2, SpecialQuota: 2},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_13",
			PrettyName:            "Религиоведение",
			RegularAnchor:         "13_02_1_05",
			BVIAnchor:             "13_02_1_05_bvi",
			TargetQuotaAnchors:    []string{"13_02_1_07"},
			DedicatedQuotaAnchors: []string{"13_02_1_08_1", "13_02_1_08_2"},
			SpecialQuotaAnchors:   []string{"13_02_1_06"},
			Capacities:            core.Capacities{Regular: 8, TargetQuota: 2, DedicatedQuota: 4, SpecialQuota: 4},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_13",
			PrettyName:            "Философия",
			RegularAnchor:         "13_02_1_01",
			BVIAnchor:             "13_02_1_01_bvi",
			TargetQuotaAnchors:    []string{"13_02_1_03"},
			DedicatedQuotaAnchors: []string{"13_02_1_04_1", "13_02_1_04_2"},
			SpecialQuotaAnchors:   []string{"13_02_1_02"},
			Capacities:            core.Capacities{Regular: 52, TargetQuota: 4, DedicatedQuota: 7, SpecialQuota: 7},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_21",
			PrettyName:            "Биоинженерия и биоинформатика",
			RegularAnchor:         "21_01_1_01",
			BVIAnchor:             "21_01_1_01_bvi",
			TargetQuotaAnchors:    []string{"21_01_1_08", "21_01_1_07", "21_01_1_03"},
			DedicatedQuotaAnchors: []string{"21_01_1_04_1", "21_01_1_04_2"},
			SpecialQuotaAnchors:   []string{"21_01_1_02"},
			Capacities:            core.Capacities{Regular: 19, TargetQuota: 8, DedicatedQuota: 4, SpecialQuota: 4},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_36",
			PrettyName:            "Лингвистика",
			RegularAnchor:         "36_02_1_01",
			BVIAnchor:             "",
			TargetQuotaAnchors:    []string{},
			DedicatedQuotaAnchors: []string{},
			SpecialQuotaAnchors:   []string{},
			Capacities:            core.Capacities{Regular: 20, TargetQuota: 1, DedicatedQuota: 3, SpecialQuota: 3},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_36",
			PrettyName:            "Перевод и переводоведение",
			RegularAnchor:         "36_01_1_01",
			BVIAnchor:             "36_01_1_01_bvi",
			TargetQuotaAnchors:    []string{},
			DedicatedQuotaAnchors: []string{"36_01_1_04_1", "36_01_1_04_2"},
			SpecialQuotaAnchors:   []string{"36_01_1_02"},
			Capacities:            core.Capacities{Regular: 8, TargetQuota: 0, DedicatedQuota: 1, SpecialQuota: 1},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_20",
			PrettyName:            "Зарубежное регионоведение",
			RegularAnchor:         "20_02_1_05",
			BVIAnchor:             "20_02_1_05_bvi",
			TargetQuotaAnchors:    []string{"20_02_1_07"},
			DedicatedQuotaAnchors: []string{"20_02_1_08_1", "20_02_1_08_2"},
			SpecialQuotaAnchors:   []string{"20_02_1_06"},
			Capacities:            core.Capacities{Regular: 6, TargetQuota: 1, DedicatedQuota: 1, SpecialQuota: 1},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_20",
			PrettyName:            "Культурология",
			RegularAnchor:         "20_02_1_12",
			BVIAnchor:             "20_02_1_12_bvi",
			TargetQuotaAnchors:    []string{},
			DedicatedQuotaAnchors: []string{"20_02_1_14_1", "20_02_1_14_2"},
			SpecialQuotaAnchors:   []string{"20_02_1_13"},
			Capacities:            core.Capacities{Regular: 5, TargetQuota: 0, DedicatedQuota: 1, SpecialQuota: 1},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_20",
			PrettyName:            "Лингвистика",
			RegularAnchor:         "20_02_1_01",
			BVIAnchor:             "20_02_1_01_bvi",
			TargetQuotaAnchors:    []string{"20_02_1_03"},
			DedicatedQuotaAnchors: []string{"20_02_1_04_1", "20_02_1_04_2"},
			SpecialQuotaAnchors:   []string{"20_02_1_02"},
			Capacities:            core.Capacities{Regular: 20, TargetQuota: 1, DedicatedQuota: 3, SpecialQuota: 3},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_20",
			PrettyName:            "Перевод и переводоведение",
			RegularAnchor:         "20_01_1_01",
			BVIAnchor:             "20_01_1_01_bvi",
			TargetQuotaAnchors:    []string{},
			DedicatedQuotaAnchors: []string{"20_01_1_04_1", "20_01_1_04_2"},
			SpecialQuotaAnchors:   []string{"20_01_1_02"},
			Capacities:            core.Capacities{Regular: 8, TargetQuota: 0, DedicatedQuota: 1, SpecialQuota: 1},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_20",
			PrettyName:            "Регионоведение россии",
			RegularAnchor:         "20_02_1_09",
			BVIAnchor:             "",
			TargetQuotaAnchors:    []string{},
			DedicatedQuotaAnchors: []string{"20_02_1_11_1", "20_02_1_11_2"},
			SpecialQuotaAnchors:   []string{"20_02_1_10"},
			Capacities:            core.Capacities{Regular: 6, TargetQuota: 0, DedicatedQuota: 1, SpecialQuota: 1},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_35",
			PrettyName:            "Международное гуманитарное сотрудничество",
			RegularAnchor:         "35_02_1_11",
			BVIAnchor:             "",
			TargetQuotaAnchors:    []string{"35_02_1_13"},
			DedicatedQuotaAnchors: []string{"35_02_1_14_1", "35_02_1_14_2"},
			SpecialQuotaAnchors:   []string{"35_02_1_12"},
			Capacities:            core.Capacities{Regular: 2, TargetQuota: 1, DedicatedQuota: 1, SpecialQuota: 1},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_04",
			PrettyName:            "Фундаментальная и прикладная химия",
			RegularAnchor:         "04_01_1_01",
			BVIAnchor:             "04_01_1_01_bvi",
			TargetQuotaAnchors:    []string{"04_01_1_07", "04_01_1_03"},
			DedicatedQuotaAnchors: []string{"04_01_1_04_1", "04_01_1_04_2"},
			SpecialQuotaAnchors:   []string{"04_01_1_02"},
			Capacities:            core.Capacities{Regular: 149, TargetQuota: 22, DedicatedQuota: 22, SpecialQuota: 22},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_88",
			PrettyName:            "Менеджмент",
			RegularAnchor:         "88_02_1_11",
			BVIAnchor:             "",
			TargetQuotaAnchors:    []string{"88_02_1_13"},
			DedicatedQuotaAnchors: []string{"88_02_1_14_1", "88_02_1_14_2"},
			SpecialQuotaAnchors:   []string{"88_02_1_12"},
			Capacities:            core.Capacities{Regular: 15, TargetQuota: 1, DedicatedQuota: 2, SpecialQuota: 2},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_88",
			PrettyName:            "Прикладная математика и информатика",
			RegularAnchor:         "88_02_1_01",
			BVIAnchor:             "",
			TargetQuotaAnchors:    []string{"88_02_1_03"},
			DedicatedQuotaAnchors: []string{"88_02_1_04_1", "88_02_1_04_2"},
			SpecialQuotaAnchors:   []string{"88_02_1_02"},
			Capacities:            core.Capacities{Regular: 7, TargetQuota: 2, DedicatedQuota: 3, SpecialQuota: 3},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_88",
			PrettyName:            "Фармация",
			RegularAnchor:         "88_01_1_06",
			BVIAnchor:             "",
			TargetQuotaAnchors:    []string{"88_01_1_08"},
			DedicatedQuotaAnchors: []string{"88_01_1_09_1", "88_01_1_09_2"},
			SpecialQuotaAnchors:   []string{"88_01_1_07"},
			Capacities:            core.Capacities{Regular: 13, TargetQuota: 3, DedicatedQuota: 2, SpecialQuota: 2},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_88",
			PrettyName:            "Фундаментальная и прикладная биология",
			RegularAnchor:         "88_01_1_01",
			BVIAnchor:             "",
			TargetQuotaAnchors:    []string{"88_01_1_03"},
			DedicatedQuotaAnchors: []string{"88_01_1_04_1", "88_01_1_04_2"},
			SpecialQuotaAnchors:   []string{"88_01_1_02"},
			Capacities:            core.Capacities{Regular: 7, TargetQuota: 5, DedicatedQuota: 4, SpecialQuota: 4},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_88",
			PrettyName:            "Юриспруденция",
			RegularAnchor:         "88_02_1_06",
			BVIAnchor:             "",
			TargetQuotaAnchors:    []string{"88_02_1_08"},
			DedicatedQuotaAnchors: []string{"88_02_1_09_1", "88_02_1_09_2"},
			SpecialQuotaAnchors:   []string{"88_02_1_07"},
			Capacities:            core.Capacities{Regular: 14, TargetQuota: 2, DedicatedQuota: 2, SpecialQuota: 2},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_06",
			PrettyName:            "Почвоведение",
			RegularAnchor:         "06_02_1_01",
			BVIAnchor:             "06_02_1_01_bvi",
			TargetQuotaAnchors:    []string{"06_02_1_03"},
			DedicatedQuotaAnchors: []string{"06_02_1_04_1", "06_02_1_04_2"},
			SpecialQuotaAnchors:   []string{"06_02_1_02"},
			Capacities:            core.Capacities{Regular: 39, TargetQuota: 5, DedicatedQuota: 8, SpecialQuota: 8},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_06",
			PrettyName:            "Экология и природопользование",
			RegularAnchor:         "06_02_1_05",
			BVIAnchor:             "",
			TargetQuotaAnchors:    []string{"06_02_1_07"},
			DedicatedQuotaAnchors: []string{"06_02_1_08_1", "06_02_1_08_2"},
			SpecialQuotaAnchors:   []string{"06_02_1_06"},
			Capacities:            core.Capacities{Regular: 10, TargetQuota: 2, DedicatedQuota: 2, SpecialQuota: 2},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_22",
			PrettyName:            "Прикладные математика и физика",
			RegularAnchor:         "22_02_1_01",
			BVIAnchor:             "",
			TargetQuotaAnchors:    []string{"22_02_1_07", "22_02_1_03"},
			DedicatedQuotaAnchors: []string{"22_02_1_04_1", "22_02_1_04_2"},
			SpecialQuotaAnchors:   []string{"22_02_1_02"},
			Capacities:            core.Capacities{Regular: 13, TargetQuota: 2, DedicatedQuota: 2, SpecialQuota: 2},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_19",
			PrettyName:            "Публичная политика и социальные науки",
			RegularAnchor:         "19_02_1_05",
			BVIAnchor:             "",
			TargetQuotaAnchors:    []string{"19_02_1_07"},
			DedicatedQuotaAnchors: []string{"19_02_1_08_1", "19_02_1_08_2"},
			SpecialQuotaAnchors:   []string{"19_02_1_06"},
			Capacities:            core.Capacities{Regular: 14, TargetQuota: 1, DedicatedQuota: 3, SpecialQuota: 3},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_19",
			PrettyName:            "Социология",
			RegularAnchor:         "19_02_1_01",
			BVIAnchor:             "",
			TargetQuotaAnchors:    []string{"19_02_1_03"},
			DedicatedQuotaAnchors: []string{"19_02_1_04_1", "19_02_1_04_2"},
			SpecialQuotaAnchors:   []string{"19_02_1_02"},
			Capacities:            core.Capacities{Regular: 11, TargetQuota: 2, DedicatedQuota: 4, SpecialQuota: 4},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_38",
			PrettyName:            "Биотехнология",
			RegularAnchor:         "38_02_1_01",
			BVIAnchor:             "",
			TargetQuotaAnchors:    []string{"38_02_1_03"},
			DedicatedQuotaAnchors: []string{"38_02_1_04_1", "38_02_1_04_2"},
			SpecialQuotaAnchors:   []string{"38_02_1_02"},
			Capacities:            core.Capacities{Regular: 14, TargetQuota: 2, DedicatedQuota: 2, SpecialQuota: 2},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_26",
			PrettyName:            "Телевидение",
			RegularAnchor:         "26_02_1_01",
			BVIAnchor:             "26_02_1_01_bvi",
			TargetQuotaAnchors:    []string{"26_02_1_03"},
			DedicatedQuotaAnchors: []string{"26_02_1_04_1", "26_02_1_04_2"},
			SpecialQuotaAnchors:   []string{"26_02_1_02"},
			Capacities:            core.Capacities{Regular: 8, TargetQuota: 1, DedicatedQuota: 2, SpecialQuota: 2},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_25",
			PrettyName:            "Экономика",
			RegularAnchor:         "25_02_1_01",
			BVIAnchor:             "25_02_1_01_bvi",
			TargetQuotaAnchors:    []string{"25_02_1_03"},
			DedicatedQuotaAnchors: []string{"25_02_1_04_1", "25_02_1_04_2"},
			SpecialQuotaAnchors:   []string{"25_02_1_02"},
			Capacities:            core.Capacities{Regular: 7, TargetQuota: 1, DedicatedQuota: 1, SpecialQuota: 1},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_25",
			PrettyName:            "Юриспруденция",
			RegularAnchor:         "25_02_1_06",
			BVIAnchor:             "25_02_1_06_bvi",
			TargetQuotaAnchors:    []string{"25_02_1_13", "25_02_1_08"},
			DedicatedQuotaAnchors: []string{"25_02_1_09_1", "25_02_1_09_2"},
			SpecialQuotaAnchors:   []string{"25_02_1_07"},
			Capacities:            core.Capacities{Regular: 14, TargetQuota: 2, DedicatedQuota: 2, SpecialQuota: 2},
		},

		&msu.HTTPHeadingSource{
			FacultyURL:            "https://cpk.msu.ru/rating/dep_09",
			PrettyName:            "Химия, физика и механика материалов",
			RegularAnchor:         "09_02_1_01",
			BVIAnchor:             "",
			TargetQuotaAnchors:    []string{"09_02_1_03"},
			DedicatedQuotaAnchors: []string{"09_02_1_04_1", "09_02_1_04_2"},
			SpecialQuotaAnchors:   []string{"09_02_1_02"},
			Capacities:            core.Capacities{Regular: 18, TargetQuota: 4, DedicatedQuota: 3, SpecialQuota: 3},
		},

		// --- Headings with anomalies (negative Regular capacity) ---
		//	&msu.HTTPHeadingSource{
		//		FacultyURL: "https://cpk.msu.ru/rating/dep_35",
		//		PrettyName: "Глобальные политические процессы и дипломатия",
		//		RegularAnchor: "35_02_1_01",
		//		BVIAnchor: "35_02_1_01_bvi",
		//		TargetQuotaAnchors: []string{"35_02_1_03"} ,
		//		DedicatedQuotaAnchors: []string{"35_02_1_04_1", "35_02_1_04_2"} ,
		//		SpecialQuotaAnchors: []string{"35_02_1_02"} ,
		//		Capacities: core.Capacities{Regular: -2, TargetQuota: 3, DedicatedQuota: 2, SpecialQuota: 2},
		//	},

	}
}
