// Code generated by ent, DO NOT EDIT.

package metadata

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the metadata type in the database.
	Label = "metadata"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldLastApplicationsIteration holds the string denoting the last_applications_iteration field in the database.
	FieldLastApplicationsIteration = "last_applications_iteration"
	// FieldLastCalculationsIteration holds the string denoting the last_calculations_iteration field in the database.
	FieldLastCalculationsIteration = "last_calculations_iteration"
	// FieldLastDrainedResultsIteration holds the string denoting the last_drained_results_iteration field in the database.
	FieldLastDrainedResultsIteration = "last_drained_results_iteration"
	// FieldUploadingLock holds the string denoting the uploading_lock field in the database.
	FieldUploadingLock = "uploading_lock"
	// Table holds the table name of the metadata in the database.
	Table = "metadata"
)

// Columns holds all SQL columns for metadata fields.
var Columns = []string{
	FieldID,
	FieldLastApplicationsIteration,
	FieldLastCalculationsIteration,
	FieldLastDrainedResultsIteration,
	FieldUploadingLock,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Metadata queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByLastApplicationsIteration orders the results by the last_applications_iteration field.
func ByLastApplicationsIteration(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastApplicationsIteration, opts...).ToFunc()
}

// ByLastCalculationsIteration orders the results by the last_calculations_iteration field.
func ByLastCalculationsIteration(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastCalculationsIteration, opts...).ToFunc()
}

// ByLastDrainedResultsIteration orders the results by the last_drained_results_iteration field.
func ByLastDrainedResultsIteration(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastDrainedResultsIteration, opts...).ToFunc()
}

// ByUploadingLock orders the results by the uploading_lock field.
func ByUploadingLock(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUploadingLock, opts...).ToFunc()
}
