// Code generated by ent, DO NOT EDIT.

package metadata

import (
	"analabit/core/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Metadata {
	return predicate.Metadata(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Metadata {
	return predicate.Metadata(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Metadata {
	return predicate.Metadata(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Metadata {
	return predicate.Metadata(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Metadata {
	return predicate.Metadata(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Metadata {
	return predicate.Metadata(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Metadata {
	return predicate.Metadata(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Metadata {
	return predicate.Metadata(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Metadata {
	return predicate.Metadata(sql.FieldLTE(FieldID, id))
}

// LastApplicationsIteration applies equality check predicate on the "last_applications_iteration" field. It's identical to LastApplicationsIterationEQ.
func LastApplicationsIteration(v int) predicate.Metadata {
	return predicate.Metadata(sql.FieldEQ(FieldLastApplicationsIteration, v))
}

// LastCalculationsIteration applies equality check predicate on the "last_calculations_iteration" field. It's identical to LastCalculationsIterationEQ.
func LastCalculationsIteration(v int) predicate.Metadata {
	return predicate.Metadata(sql.FieldEQ(FieldLastCalculationsIteration, v))
}

// LastDrainedResultsIteration applies equality check predicate on the "last_drained_results_iteration" field. It's identical to LastDrainedResultsIterationEQ.
func LastDrainedResultsIteration(v int) predicate.Metadata {
	return predicate.Metadata(sql.FieldEQ(FieldLastDrainedResultsIteration, v))
}

// UploadingLock applies equality check predicate on the "uploading_lock" field. It's identical to UploadingLockEQ.
func UploadingLock(v bool) predicate.Metadata {
	return predicate.Metadata(sql.FieldEQ(FieldUploadingLock, v))
}

// LastApplicationsIterationEQ applies the EQ predicate on the "last_applications_iteration" field.
func LastApplicationsIterationEQ(v int) predicate.Metadata {
	return predicate.Metadata(sql.FieldEQ(FieldLastApplicationsIteration, v))
}

// LastApplicationsIterationNEQ applies the NEQ predicate on the "last_applications_iteration" field.
func LastApplicationsIterationNEQ(v int) predicate.Metadata {
	return predicate.Metadata(sql.FieldNEQ(FieldLastApplicationsIteration, v))
}

// LastApplicationsIterationIn applies the In predicate on the "last_applications_iteration" field.
func LastApplicationsIterationIn(vs ...int) predicate.Metadata {
	return predicate.Metadata(sql.FieldIn(FieldLastApplicationsIteration, vs...))
}

// LastApplicationsIterationNotIn applies the NotIn predicate on the "last_applications_iteration" field.
func LastApplicationsIterationNotIn(vs ...int) predicate.Metadata {
	return predicate.Metadata(sql.FieldNotIn(FieldLastApplicationsIteration, vs...))
}

// LastApplicationsIterationGT applies the GT predicate on the "last_applications_iteration" field.
func LastApplicationsIterationGT(v int) predicate.Metadata {
	return predicate.Metadata(sql.FieldGT(FieldLastApplicationsIteration, v))
}

// LastApplicationsIterationGTE applies the GTE predicate on the "last_applications_iteration" field.
func LastApplicationsIterationGTE(v int) predicate.Metadata {
	return predicate.Metadata(sql.FieldGTE(FieldLastApplicationsIteration, v))
}

// LastApplicationsIterationLT applies the LT predicate on the "last_applications_iteration" field.
func LastApplicationsIterationLT(v int) predicate.Metadata {
	return predicate.Metadata(sql.FieldLT(FieldLastApplicationsIteration, v))
}

// LastApplicationsIterationLTE applies the LTE predicate on the "last_applications_iteration" field.
func LastApplicationsIterationLTE(v int) predicate.Metadata {
	return predicate.Metadata(sql.FieldLTE(FieldLastApplicationsIteration, v))
}

// LastCalculationsIterationEQ applies the EQ predicate on the "last_calculations_iteration" field.
func LastCalculationsIterationEQ(v int) predicate.Metadata {
	return predicate.Metadata(sql.FieldEQ(FieldLastCalculationsIteration, v))
}

// LastCalculationsIterationNEQ applies the NEQ predicate on the "last_calculations_iteration" field.
func LastCalculationsIterationNEQ(v int) predicate.Metadata {
	return predicate.Metadata(sql.FieldNEQ(FieldLastCalculationsIteration, v))
}

// LastCalculationsIterationIn applies the In predicate on the "last_calculations_iteration" field.
func LastCalculationsIterationIn(vs ...int) predicate.Metadata {
	return predicate.Metadata(sql.FieldIn(FieldLastCalculationsIteration, vs...))
}

// LastCalculationsIterationNotIn applies the NotIn predicate on the "last_calculations_iteration" field.
func LastCalculationsIterationNotIn(vs ...int) predicate.Metadata {
	return predicate.Metadata(sql.FieldNotIn(FieldLastCalculationsIteration, vs...))
}

// LastCalculationsIterationGT applies the GT predicate on the "last_calculations_iteration" field.
func LastCalculationsIterationGT(v int) predicate.Metadata {
	return predicate.Metadata(sql.FieldGT(FieldLastCalculationsIteration, v))
}

// LastCalculationsIterationGTE applies the GTE predicate on the "last_calculations_iteration" field.
func LastCalculationsIterationGTE(v int) predicate.Metadata {
	return predicate.Metadata(sql.FieldGTE(FieldLastCalculationsIteration, v))
}

// LastCalculationsIterationLT applies the LT predicate on the "last_calculations_iteration" field.
func LastCalculationsIterationLT(v int) predicate.Metadata {
	return predicate.Metadata(sql.FieldLT(FieldLastCalculationsIteration, v))
}

// LastCalculationsIterationLTE applies the LTE predicate on the "last_calculations_iteration" field.
func LastCalculationsIterationLTE(v int) predicate.Metadata {
	return predicate.Metadata(sql.FieldLTE(FieldLastCalculationsIteration, v))
}

// LastDrainedResultsIterationEQ applies the EQ predicate on the "last_drained_results_iteration" field.
func LastDrainedResultsIterationEQ(v int) predicate.Metadata {
	return predicate.Metadata(sql.FieldEQ(FieldLastDrainedResultsIteration, v))
}

// LastDrainedResultsIterationNEQ applies the NEQ predicate on the "last_drained_results_iteration" field.
func LastDrainedResultsIterationNEQ(v int) predicate.Metadata {
	return predicate.Metadata(sql.FieldNEQ(FieldLastDrainedResultsIteration, v))
}

// LastDrainedResultsIterationIn applies the In predicate on the "last_drained_results_iteration" field.
func LastDrainedResultsIterationIn(vs ...int) predicate.Metadata {
	return predicate.Metadata(sql.FieldIn(FieldLastDrainedResultsIteration, vs...))
}

// LastDrainedResultsIterationNotIn applies the NotIn predicate on the "last_drained_results_iteration" field.
func LastDrainedResultsIterationNotIn(vs ...int) predicate.Metadata {
	return predicate.Metadata(sql.FieldNotIn(FieldLastDrainedResultsIteration, vs...))
}

// LastDrainedResultsIterationGT applies the GT predicate on the "last_drained_results_iteration" field.
func LastDrainedResultsIterationGT(v int) predicate.Metadata {
	return predicate.Metadata(sql.FieldGT(FieldLastDrainedResultsIteration, v))
}

// LastDrainedResultsIterationGTE applies the GTE predicate on the "last_drained_results_iteration" field.
func LastDrainedResultsIterationGTE(v int) predicate.Metadata {
	return predicate.Metadata(sql.FieldGTE(FieldLastDrainedResultsIteration, v))
}

// LastDrainedResultsIterationLT applies the LT predicate on the "last_drained_results_iteration" field.
func LastDrainedResultsIterationLT(v int) predicate.Metadata {
	return predicate.Metadata(sql.FieldLT(FieldLastDrainedResultsIteration, v))
}

// LastDrainedResultsIterationLTE applies the LTE predicate on the "last_drained_results_iteration" field.
func LastDrainedResultsIterationLTE(v int) predicate.Metadata {
	return predicate.Metadata(sql.FieldLTE(FieldLastDrainedResultsIteration, v))
}

// UploadingLockEQ applies the EQ predicate on the "uploading_lock" field.
func UploadingLockEQ(v bool) predicate.Metadata {
	return predicate.Metadata(sql.FieldEQ(FieldUploadingLock, v))
}

// UploadingLockNEQ applies the NEQ predicate on the "uploading_lock" field.
func UploadingLockNEQ(v bool) predicate.Metadata {
	return predicate.Metadata(sql.FieldNEQ(FieldUploadingLock, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Metadata) predicate.Metadata {
	return predicate.Metadata(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Metadata) predicate.Metadata {
	return predicate.Metadata(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Metadata) predicate.Metadata {
	return predicate.Metadata(sql.NotPredicates(p))
}
