// Code generated by ent, DO NOT EDIT.

package ent

import (
	"analabit/core/ent/drainedresult"
	"analabit/core/ent/heading"
	"analabit/core/ent/run"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DrainedResultCreate is the builder for creating a DrainedResult entity.
type DrainedResultCreate struct {
	config
	mutation *DrainedResultMutation
	hooks    []Hook
}

// SetDrainedPercent sets the "drained_percent" field.
func (drc *DrainedResultCreate) SetDrainedPercent(i int) *DrainedResultCreate {
	drc.mutation.SetDrainedPercent(i)
	return drc
}

// SetAvgPassingScore sets the "avg_passing_score" field.
func (drc *DrainedResultCreate) SetAvgPassingScore(i int) *DrainedResultCreate {
	drc.mutation.SetAvgPassingScore(i)
	return drc
}

// SetMinPassingScore sets the "min_passing_score" field.
func (drc *DrainedResultCreate) SetMinPassingScore(i int) *DrainedResultCreate {
	drc.mutation.SetMinPassingScore(i)
	return drc
}

// SetMaxPassingScore sets the "max_passing_score" field.
func (drc *DrainedResultCreate) SetMaxPassingScore(i int) *DrainedResultCreate {
	drc.mutation.SetMaxPassingScore(i)
	return drc
}

// SetMedPassingScore sets the "med_passing_score" field.
func (drc *DrainedResultCreate) SetMedPassingScore(i int) *DrainedResultCreate {
	drc.mutation.SetMedPassingScore(i)
	return drc
}

// SetAvgLastAdmittedRatingPlace sets the "avg_last_admitted_rating_place" field.
func (drc *DrainedResultCreate) SetAvgLastAdmittedRatingPlace(i int) *DrainedResultCreate {
	drc.mutation.SetAvgLastAdmittedRatingPlace(i)
	return drc
}

// SetMinLastAdmittedRatingPlace sets the "min_last_admitted_rating_place" field.
func (drc *DrainedResultCreate) SetMinLastAdmittedRatingPlace(i int) *DrainedResultCreate {
	drc.mutation.SetMinLastAdmittedRatingPlace(i)
	return drc
}

// SetMaxLastAdmittedRatingPlace sets the "max_last_admitted_rating_place" field.
func (drc *DrainedResultCreate) SetMaxLastAdmittedRatingPlace(i int) *DrainedResultCreate {
	drc.mutation.SetMaxLastAdmittedRatingPlace(i)
	return drc
}

// SetMedLastAdmittedRatingPlace sets the "med_last_admitted_rating_place" field.
func (drc *DrainedResultCreate) SetMedLastAdmittedRatingPlace(i int) *DrainedResultCreate {
	drc.mutation.SetMedLastAdmittedRatingPlace(i)
	return drc
}

// SetIteration sets the "iteration" field.
func (drc *DrainedResultCreate) SetIteration(i int) *DrainedResultCreate {
	drc.mutation.SetIteration(i)
	return drc
}

// SetRunID sets the "run_id" field.
func (drc *DrainedResultCreate) SetRunID(i int) *DrainedResultCreate {
	drc.mutation.SetRunID(i)
	return drc
}

// SetHeadingID sets the "heading" edge to the Heading entity by ID.
func (drc *DrainedResultCreate) SetHeadingID(id int) *DrainedResultCreate {
	drc.mutation.SetHeadingID(id)
	return drc
}

// SetHeading sets the "heading" edge to the Heading entity.
func (drc *DrainedResultCreate) SetHeading(h *Heading) *DrainedResultCreate {
	return drc.SetHeadingID(h.ID)
}

// SetRun sets the "run" edge to the Run entity.
func (drc *DrainedResultCreate) SetRun(r *Run) *DrainedResultCreate {
	return drc.SetRunID(r.ID)
}

// Mutation returns the DrainedResultMutation object of the builder.
func (drc *DrainedResultCreate) Mutation() *DrainedResultMutation {
	return drc.mutation
}

// Save creates the DrainedResult in the database.
func (drc *DrainedResultCreate) Save(ctx context.Context) (*DrainedResult, error) {
	return withHooks(ctx, drc.sqlSave, drc.mutation, drc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (drc *DrainedResultCreate) SaveX(ctx context.Context) *DrainedResult {
	v, err := drc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (drc *DrainedResultCreate) Exec(ctx context.Context) error {
	_, err := drc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (drc *DrainedResultCreate) ExecX(ctx context.Context) {
	if err := drc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (drc *DrainedResultCreate) check() error {
	if _, ok := drc.mutation.DrainedPercent(); !ok {
		return &ValidationError{Name: "drained_percent", err: errors.New(`ent: missing required field "DrainedResult.drained_percent"`)}
	}
	if _, ok := drc.mutation.AvgPassingScore(); !ok {
		return &ValidationError{Name: "avg_passing_score", err: errors.New(`ent: missing required field "DrainedResult.avg_passing_score"`)}
	}
	if _, ok := drc.mutation.MinPassingScore(); !ok {
		return &ValidationError{Name: "min_passing_score", err: errors.New(`ent: missing required field "DrainedResult.min_passing_score"`)}
	}
	if _, ok := drc.mutation.MaxPassingScore(); !ok {
		return &ValidationError{Name: "max_passing_score", err: errors.New(`ent: missing required field "DrainedResult.max_passing_score"`)}
	}
	if _, ok := drc.mutation.MedPassingScore(); !ok {
		return &ValidationError{Name: "med_passing_score", err: errors.New(`ent: missing required field "DrainedResult.med_passing_score"`)}
	}
	if _, ok := drc.mutation.AvgLastAdmittedRatingPlace(); !ok {
		return &ValidationError{Name: "avg_last_admitted_rating_place", err: errors.New(`ent: missing required field "DrainedResult.avg_last_admitted_rating_place"`)}
	}
	if _, ok := drc.mutation.MinLastAdmittedRatingPlace(); !ok {
		return &ValidationError{Name: "min_last_admitted_rating_place", err: errors.New(`ent: missing required field "DrainedResult.min_last_admitted_rating_place"`)}
	}
	if _, ok := drc.mutation.MaxLastAdmittedRatingPlace(); !ok {
		return &ValidationError{Name: "max_last_admitted_rating_place", err: errors.New(`ent: missing required field "DrainedResult.max_last_admitted_rating_place"`)}
	}
	if _, ok := drc.mutation.MedLastAdmittedRatingPlace(); !ok {
		return &ValidationError{Name: "med_last_admitted_rating_place", err: errors.New(`ent: missing required field "DrainedResult.med_last_admitted_rating_place"`)}
	}
	if _, ok := drc.mutation.Iteration(); !ok {
		return &ValidationError{Name: "iteration", err: errors.New(`ent: missing required field "DrainedResult.iteration"`)}
	}
	if _, ok := drc.mutation.RunID(); !ok {
		return &ValidationError{Name: "run_id", err: errors.New(`ent: missing required field "DrainedResult.run_id"`)}
	}
	if len(drc.mutation.HeadingIDs()) == 0 {
		return &ValidationError{Name: "heading", err: errors.New(`ent: missing required edge "DrainedResult.heading"`)}
	}
	if len(drc.mutation.RunIDs()) == 0 {
		return &ValidationError{Name: "run", err: errors.New(`ent: missing required edge "DrainedResult.run"`)}
	}
	return nil
}

func (drc *DrainedResultCreate) sqlSave(ctx context.Context) (*DrainedResult, error) {
	if err := drc.check(); err != nil {
		return nil, err
	}
	_node, _spec := drc.createSpec()
	if err := sqlgraph.CreateNode(ctx, drc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	drc.mutation.id = &_node.ID
	drc.mutation.done = true
	return _node, nil
}

func (drc *DrainedResultCreate) createSpec() (*DrainedResult, *sqlgraph.CreateSpec) {
	var (
		_node = &DrainedResult{config: drc.config}
		_spec = sqlgraph.NewCreateSpec(drainedresult.Table, sqlgraph.NewFieldSpec(drainedresult.FieldID, field.TypeInt))
	)
	if value, ok := drc.mutation.DrainedPercent(); ok {
		_spec.SetField(drainedresult.FieldDrainedPercent, field.TypeInt, value)
		_node.DrainedPercent = value
	}
	if value, ok := drc.mutation.AvgPassingScore(); ok {
		_spec.SetField(drainedresult.FieldAvgPassingScore, field.TypeInt, value)
		_node.AvgPassingScore = value
	}
	if value, ok := drc.mutation.MinPassingScore(); ok {
		_spec.SetField(drainedresult.FieldMinPassingScore, field.TypeInt, value)
		_node.MinPassingScore = value
	}
	if value, ok := drc.mutation.MaxPassingScore(); ok {
		_spec.SetField(drainedresult.FieldMaxPassingScore, field.TypeInt, value)
		_node.MaxPassingScore = value
	}
	if value, ok := drc.mutation.MedPassingScore(); ok {
		_spec.SetField(drainedresult.FieldMedPassingScore, field.TypeInt, value)
		_node.MedPassingScore = value
	}
	if value, ok := drc.mutation.AvgLastAdmittedRatingPlace(); ok {
		_spec.SetField(drainedresult.FieldAvgLastAdmittedRatingPlace, field.TypeInt, value)
		_node.AvgLastAdmittedRatingPlace = value
	}
	if value, ok := drc.mutation.MinLastAdmittedRatingPlace(); ok {
		_spec.SetField(drainedresult.FieldMinLastAdmittedRatingPlace, field.TypeInt, value)
		_node.MinLastAdmittedRatingPlace = value
	}
	if value, ok := drc.mutation.MaxLastAdmittedRatingPlace(); ok {
		_spec.SetField(drainedresult.FieldMaxLastAdmittedRatingPlace, field.TypeInt, value)
		_node.MaxLastAdmittedRatingPlace = value
	}
	if value, ok := drc.mutation.MedLastAdmittedRatingPlace(); ok {
		_spec.SetField(drainedresult.FieldMedLastAdmittedRatingPlace, field.TypeInt, value)
		_node.MedLastAdmittedRatingPlace = value
	}
	if value, ok := drc.mutation.Iteration(); ok {
		_spec.SetField(drainedresult.FieldIteration, field.TypeInt, value)
		_node.Iteration = value
	}
	if nodes := drc.mutation.HeadingIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   drainedresult.HeadingTable,
			Columns: []string{drainedresult.HeadingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(heading.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.heading_drained_results = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := drc.mutation.RunIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   drainedresult.RunTable,
			Columns: []string{drainedresult.RunColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(run.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RunID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// DrainedResultCreateBulk is the builder for creating many DrainedResult entities in bulk.
type DrainedResultCreateBulk struct {
	config
	err      error
	builders []*DrainedResultCreate
}

// Save creates the DrainedResult entities in the database.
func (drcb *DrainedResultCreateBulk) Save(ctx context.Context) ([]*DrainedResult, error) {
	if drcb.err != nil {
		return nil, drcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(drcb.builders))
	nodes := make([]*DrainedResult, len(drcb.builders))
	mutators := make([]Mutator, len(drcb.builders))
	for i := range drcb.builders {
		func(i int, root context.Context) {
			builder := drcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DrainedResultMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, drcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, drcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, drcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (drcb *DrainedResultCreateBulk) SaveX(ctx context.Context) []*DrainedResult {
	v, err := drcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (drcb *DrainedResultCreateBulk) Exec(ctx context.Context) error {
	_, err := drcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (drcb *DrainedResultCreateBulk) ExecX(ctx context.Context) {
	if err := drcb.Exec(ctx); err != nil {
		panic(err)
	}
}
