// Code generated by ent, DO NOT EDIT.

package ent

import (
	"analabit/core/ent/drainedresult"
	"analabit/core/ent/heading"
	"analabit/core/ent/predicate"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DrainedResultUpdate is the builder for updating DrainedResult entities.
type DrainedResultUpdate struct {
	config
	hooks    []Hook
	mutation *DrainedResultMutation
}

// Where appends a list predicates to the DrainedResultUpdate builder.
func (dru *DrainedResultUpdate) Where(ps ...predicate.DrainedResult) *DrainedResultUpdate {
	dru.mutation.Where(ps...)
	return dru
}

// SetDrainedPercent sets the "drained_percent" field.
func (dru *DrainedResultUpdate) SetDrainedPercent(i int) *DrainedResultUpdate {
	dru.mutation.ResetDrainedPercent()
	dru.mutation.SetDrainedPercent(i)
	return dru
}

// SetNillableDrainedPercent sets the "drained_percent" field if the given value is not nil.
func (dru *DrainedResultUpdate) SetNillableDrainedPercent(i *int) *DrainedResultUpdate {
	if i != nil {
		dru.SetDrainedPercent(*i)
	}
	return dru
}

// AddDrainedPercent adds i to the "drained_percent" field.
func (dru *DrainedResultUpdate) AddDrainedPercent(i int) *DrainedResultUpdate {
	dru.mutation.AddDrainedPercent(i)
	return dru
}

// SetPassingScore sets the "passing_score" field.
func (dru *DrainedResultUpdate) SetPassingScore(i int) *DrainedResultUpdate {
	dru.mutation.ResetPassingScore()
	dru.mutation.SetPassingScore(i)
	return dru
}

// SetNillablePassingScore sets the "passing_score" field if the given value is not nil.
func (dru *DrainedResultUpdate) SetNillablePassingScore(i *int) *DrainedResultUpdate {
	if i != nil {
		dru.SetPassingScore(*i)
	}
	return dru
}

// AddPassingScore adds i to the "passing_score" field.
func (dru *DrainedResultUpdate) AddPassingScore(i int) *DrainedResultUpdate {
	dru.mutation.AddPassingScore(i)
	return dru
}

// SetLastAdmittedRatingPlace sets the "last_admitted_rating_place" field.
func (dru *DrainedResultUpdate) SetLastAdmittedRatingPlace(i int) *DrainedResultUpdate {
	dru.mutation.ResetLastAdmittedRatingPlace()
	dru.mutation.SetLastAdmittedRatingPlace(i)
	return dru
}

// SetNillableLastAdmittedRatingPlace sets the "last_admitted_rating_place" field if the given value is not nil.
func (dru *DrainedResultUpdate) SetNillableLastAdmittedRatingPlace(i *int) *DrainedResultUpdate {
	if i != nil {
		dru.SetLastAdmittedRatingPlace(*i)
	}
	return dru
}

// AddLastAdmittedRatingPlace adds i to the "last_admitted_rating_place" field.
func (dru *DrainedResultUpdate) AddLastAdmittedRatingPlace(i int) *DrainedResultUpdate {
	dru.mutation.AddLastAdmittedRatingPlace(i)
	return dru
}

// SetIteration sets the "iteration" field.
func (dru *DrainedResultUpdate) SetIteration(i int) *DrainedResultUpdate {
	dru.mutation.ResetIteration()
	dru.mutation.SetIteration(i)
	return dru
}

// SetNillableIteration sets the "iteration" field if the given value is not nil.
func (dru *DrainedResultUpdate) SetNillableIteration(i *int) *DrainedResultUpdate {
	if i != nil {
		dru.SetIteration(*i)
	}
	return dru
}

// AddIteration adds i to the "iteration" field.
func (dru *DrainedResultUpdate) AddIteration(i int) *DrainedResultUpdate {
	dru.mutation.AddIteration(i)
	return dru
}

// SetHeadingID sets the "heading" edge to the Heading entity by ID.
func (dru *DrainedResultUpdate) SetHeadingID(id int) *DrainedResultUpdate {
	dru.mutation.SetHeadingID(id)
	return dru
}

// SetHeading sets the "heading" edge to the Heading entity.
func (dru *DrainedResultUpdate) SetHeading(h *Heading) *DrainedResultUpdate {
	return dru.SetHeadingID(h.ID)
}

// Mutation returns the DrainedResultMutation object of the builder.
func (dru *DrainedResultUpdate) Mutation() *DrainedResultMutation {
	return dru.mutation
}

// ClearHeading clears the "heading" edge to the Heading entity.
func (dru *DrainedResultUpdate) ClearHeading() *DrainedResultUpdate {
	dru.mutation.ClearHeading()
	return dru
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (dru *DrainedResultUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, dru.sqlSave, dru.mutation, dru.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (dru *DrainedResultUpdate) SaveX(ctx context.Context) int {
	affected, err := dru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (dru *DrainedResultUpdate) Exec(ctx context.Context) error {
	_, err := dru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dru *DrainedResultUpdate) ExecX(ctx context.Context) {
	if err := dru.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (dru *DrainedResultUpdate) check() error {
	if dru.mutation.HeadingCleared() && len(dru.mutation.HeadingIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DrainedResult.heading"`)
	}
	return nil
}

func (dru *DrainedResultUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := dru.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(drainedresult.Table, drainedresult.Columns, sqlgraph.NewFieldSpec(drainedresult.FieldID, field.TypeInt))
	if ps := dru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := dru.mutation.DrainedPercent(); ok {
		_spec.SetField(drainedresult.FieldDrainedPercent, field.TypeInt, value)
	}
	if value, ok := dru.mutation.AddedDrainedPercent(); ok {
		_spec.AddField(drainedresult.FieldDrainedPercent, field.TypeInt, value)
	}
	if value, ok := dru.mutation.PassingScore(); ok {
		_spec.SetField(drainedresult.FieldPassingScore, field.TypeInt, value)
	}
	if value, ok := dru.mutation.AddedPassingScore(); ok {
		_spec.AddField(drainedresult.FieldPassingScore, field.TypeInt, value)
	}
	if value, ok := dru.mutation.LastAdmittedRatingPlace(); ok {
		_spec.SetField(drainedresult.FieldLastAdmittedRatingPlace, field.TypeInt, value)
	}
	if value, ok := dru.mutation.AddedLastAdmittedRatingPlace(); ok {
		_spec.AddField(drainedresult.FieldLastAdmittedRatingPlace, field.TypeInt, value)
	}
	if value, ok := dru.mutation.Iteration(); ok {
		_spec.SetField(drainedresult.FieldIteration, field.TypeInt, value)
	}
	if value, ok := dru.mutation.AddedIteration(); ok {
		_spec.AddField(drainedresult.FieldIteration, field.TypeInt, value)
	}
	if dru.mutation.HeadingCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   drainedresult.HeadingTable,
			Columns: []string{drainedresult.HeadingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(heading.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := dru.mutation.HeadingIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   drainedresult.HeadingTable,
			Columns: []string{drainedresult.HeadingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(heading.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, dru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{drainedresult.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	dru.mutation.done = true
	return n, nil
}

// DrainedResultUpdateOne is the builder for updating a single DrainedResult entity.
type DrainedResultUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DrainedResultMutation
}

// SetDrainedPercent sets the "drained_percent" field.
func (druo *DrainedResultUpdateOne) SetDrainedPercent(i int) *DrainedResultUpdateOne {
	druo.mutation.ResetDrainedPercent()
	druo.mutation.SetDrainedPercent(i)
	return druo
}

// SetNillableDrainedPercent sets the "drained_percent" field if the given value is not nil.
func (druo *DrainedResultUpdateOne) SetNillableDrainedPercent(i *int) *DrainedResultUpdateOne {
	if i != nil {
		druo.SetDrainedPercent(*i)
	}
	return druo
}

// AddDrainedPercent adds i to the "drained_percent" field.
func (druo *DrainedResultUpdateOne) AddDrainedPercent(i int) *DrainedResultUpdateOne {
	druo.mutation.AddDrainedPercent(i)
	return druo
}

// SetPassingScore sets the "passing_score" field.
func (druo *DrainedResultUpdateOne) SetPassingScore(i int) *DrainedResultUpdateOne {
	druo.mutation.ResetPassingScore()
	druo.mutation.SetPassingScore(i)
	return druo
}

// SetNillablePassingScore sets the "passing_score" field if the given value is not nil.
func (druo *DrainedResultUpdateOne) SetNillablePassingScore(i *int) *DrainedResultUpdateOne {
	if i != nil {
		druo.SetPassingScore(*i)
	}
	return druo
}

// AddPassingScore adds i to the "passing_score" field.
func (druo *DrainedResultUpdateOne) AddPassingScore(i int) *DrainedResultUpdateOne {
	druo.mutation.AddPassingScore(i)
	return druo
}

// SetLastAdmittedRatingPlace sets the "last_admitted_rating_place" field.
func (druo *DrainedResultUpdateOne) SetLastAdmittedRatingPlace(i int) *DrainedResultUpdateOne {
	druo.mutation.ResetLastAdmittedRatingPlace()
	druo.mutation.SetLastAdmittedRatingPlace(i)
	return druo
}

// SetNillableLastAdmittedRatingPlace sets the "last_admitted_rating_place" field if the given value is not nil.
func (druo *DrainedResultUpdateOne) SetNillableLastAdmittedRatingPlace(i *int) *DrainedResultUpdateOne {
	if i != nil {
		druo.SetLastAdmittedRatingPlace(*i)
	}
	return druo
}

// AddLastAdmittedRatingPlace adds i to the "last_admitted_rating_place" field.
func (druo *DrainedResultUpdateOne) AddLastAdmittedRatingPlace(i int) *DrainedResultUpdateOne {
	druo.mutation.AddLastAdmittedRatingPlace(i)
	return druo
}

// SetIteration sets the "iteration" field.
func (druo *DrainedResultUpdateOne) SetIteration(i int) *DrainedResultUpdateOne {
	druo.mutation.ResetIteration()
	druo.mutation.SetIteration(i)
	return druo
}

// SetNillableIteration sets the "iteration" field if the given value is not nil.
func (druo *DrainedResultUpdateOne) SetNillableIteration(i *int) *DrainedResultUpdateOne {
	if i != nil {
		druo.SetIteration(*i)
	}
	return druo
}

// AddIteration adds i to the "iteration" field.
func (druo *DrainedResultUpdateOne) AddIteration(i int) *DrainedResultUpdateOne {
	druo.mutation.AddIteration(i)
	return druo
}

// SetHeadingID sets the "heading" edge to the Heading entity by ID.
func (druo *DrainedResultUpdateOne) SetHeadingID(id int) *DrainedResultUpdateOne {
	druo.mutation.SetHeadingID(id)
	return druo
}

// SetHeading sets the "heading" edge to the Heading entity.
func (druo *DrainedResultUpdateOne) SetHeading(h *Heading) *DrainedResultUpdateOne {
	return druo.SetHeadingID(h.ID)
}

// Mutation returns the DrainedResultMutation object of the builder.
func (druo *DrainedResultUpdateOne) Mutation() *DrainedResultMutation {
	return druo.mutation
}

// ClearHeading clears the "heading" edge to the Heading entity.
func (druo *DrainedResultUpdateOne) ClearHeading() *DrainedResultUpdateOne {
	druo.mutation.ClearHeading()
	return druo
}

// Where appends a list predicates to the DrainedResultUpdate builder.
func (druo *DrainedResultUpdateOne) Where(ps ...predicate.DrainedResult) *DrainedResultUpdateOne {
	druo.mutation.Where(ps...)
	return druo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (druo *DrainedResultUpdateOne) Select(field string, fields ...string) *DrainedResultUpdateOne {
	druo.fields = append([]string{field}, fields...)
	return druo
}

// Save executes the query and returns the updated DrainedResult entity.
func (druo *DrainedResultUpdateOne) Save(ctx context.Context) (*DrainedResult, error) {
	return withHooks(ctx, druo.sqlSave, druo.mutation, druo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (druo *DrainedResultUpdateOne) SaveX(ctx context.Context) *DrainedResult {
	node, err := druo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (druo *DrainedResultUpdateOne) Exec(ctx context.Context) error {
	_, err := druo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (druo *DrainedResultUpdateOne) ExecX(ctx context.Context) {
	if err := druo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (druo *DrainedResultUpdateOne) check() error {
	if druo.mutation.HeadingCleared() && len(druo.mutation.HeadingIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DrainedResult.heading"`)
	}
	return nil
}

func (druo *DrainedResultUpdateOne) sqlSave(ctx context.Context) (_node *DrainedResult, err error) {
	if err := druo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(drainedresult.Table, drainedresult.Columns, sqlgraph.NewFieldSpec(drainedresult.FieldID, field.TypeInt))
	id, ok := druo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DrainedResult.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := druo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, drainedresult.FieldID)
		for _, f := range fields {
			if !drainedresult.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != drainedresult.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := druo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := druo.mutation.DrainedPercent(); ok {
		_spec.SetField(drainedresult.FieldDrainedPercent, field.TypeInt, value)
	}
	if value, ok := druo.mutation.AddedDrainedPercent(); ok {
		_spec.AddField(drainedresult.FieldDrainedPercent, field.TypeInt, value)
	}
	if value, ok := druo.mutation.PassingScore(); ok {
		_spec.SetField(drainedresult.FieldPassingScore, field.TypeInt, value)
	}
	if value, ok := druo.mutation.AddedPassingScore(); ok {
		_spec.AddField(drainedresult.FieldPassingScore, field.TypeInt, value)
	}
	if value, ok := druo.mutation.LastAdmittedRatingPlace(); ok {
		_spec.SetField(drainedresult.FieldLastAdmittedRatingPlace, field.TypeInt, value)
	}
	if value, ok := druo.mutation.AddedLastAdmittedRatingPlace(); ok {
		_spec.AddField(drainedresult.FieldLastAdmittedRatingPlace, field.TypeInt, value)
	}
	if value, ok := druo.mutation.Iteration(); ok {
		_spec.SetField(drainedresult.FieldIteration, field.TypeInt, value)
	}
	if value, ok := druo.mutation.AddedIteration(); ok {
		_spec.AddField(drainedresult.FieldIteration, field.TypeInt, value)
	}
	if druo.mutation.HeadingCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   drainedresult.HeadingTable,
			Columns: []string{drainedresult.HeadingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(heading.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := druo.mutation.HeadingIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   drainedresult.HeadingTable,
			Columns: []string{drainedresult.HeadingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(heading.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &DrainedResult{config: druo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, druo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{drainedresult.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	druo.mutation.done = true
	return _node, nil
}
