// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/trueegorletov/analabit/core/ent/application"
	"github.com/trueegorletov/analabit/core/ent/calculation"
	"github.com/trueegorletov/analabit/core/ent/drainedresult"
	"github.com/trueegorletov/analabit/core/ent/heading"
	"github.com/trueegorletov/analabit/core/ent/predicate"
	"github.com/trueegorletov/analabit/core/ent/varsity"
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// HeadingQuery is the builder for querying Heading entities.
type HeadingQuery struct {
	config
	ctx                *QueryContext
	order              []heading.OrderOption
	inters             []Interceptor
	predicates         []predicate.Heading
	withVarsity        *VarsityQuery
	withApplications   *ApplicationQuery
	withCalculations   *CalculationQuery
	withDrainedResults *DrainedResultQuery
	withFKs            bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the HeadingQuery builder.
func (hq *HeadingQuery) Where(ps ...predicate.Heading) *HeadingQuery {
	hq.predicates = append(hq.predicates, ps...)
	return hq
}

// Limit the number of records to be returned by this query.
func (hq *HeadingQuery) Limit(limit int) *HeadingQuery {
	hq.ctx.Limit = &limit
	return hq
}

// Offset to start from.
func (hq *HeadingQuery) Offset(offset int) *HeadingQuery {
	hq.ctx.Offset = &offset
	return hq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (hq *HeadingQuery) Unique(unique bool) *HeadingQuery {
	hq.ctx.Unique = &unique
	return hq
}

// Order specifies how the records should be ordered.
func (hq *HeadingQuery) Order(o ...heading.OrderOption) *HeadingQuery {
	hq.order = append(hq.order, o...)
	return hq
}

// QueryVarsity chains the current query on the "varsity" edge.
func (hq *HeadingQuery) QueryVarsity() *VarsityQuery {
	query := (&VarsityClient{config: hq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := hq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := hq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(heading.Table, heading.FieldID, selector),
			sqlgraph.To(varsity.Table, varsity.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, heading.VarsityTable, heading.VarsityColumn),
		)
		fromU = sqlgraph.SetNeighbors(hq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryApplications chains the current query on the "applications" edge.
func (hq *HeadingQuery) QueryApplications() *ApplicationQuery {
	query := (&ApplicationClient{config: hq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := hq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := hq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(heading.Table, heading.FieldID, selector),
			sqlgraph.To(application.Table, application.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, heading.ApplicationsTable, heading.ApplicationsColumn),
		)
		fromU = sqlgraph.SetNeighbors(hq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCalculations chains the current query on the "calculations" edge.
func (hq *HeadingQuery) QueryCalculations() *CalculationQuery {
	query := (&CalculationClient{config: hq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := hq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := hq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(heading.Table, heading.FieldID, selector),
			sqlgraph.To(calculation.Table, calculation.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, heading.CalculationsTable, heading.CalculationsColumn),
		)
		fromU = sqlgraph.SetNeighbors(hq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryDrainedResults chains the current query on the "drained_results" edge.
func (hq *HeadingQuery) QueryDrainedResults() *DrainedResultQuery {
	query := (&DrainedResultClient{config: hq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := hq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := hq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(heading.Table, heading.FieldID, selector),
			sqlgraph.To(drainedresult.Table, drainedresult.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, heading.DrainedResultsTable, heading.DrainedResultsColumn),
		)
		fromU = sqlgraph.SetNeighbors(hq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Heading entity from the query.
// Returns a *NotFoundError when no Heading was found.
func (hq *HeadingQuery) First(ctx context.Context) (*Heading, error) {
	nodes, err := hq.Limit(1).All(setContextOp(ctx, hq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{heading.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (hq *HeadingQuery) FirstX(ctx context.Context) *Heading {
	node, err := hq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Heading ID from the query.
// Returns a *NotFoundError when no Heading ID was found.
func (hq *HeadingQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = hq.Limit(1).IDs(setContextOp(ctx, hq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{heading.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (hq *HeadingQuery) FirstIDX(ctx context.Context) int {
	id, err := hq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Heading entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Heading entity is found.
// Returns a *NotFoundError when no Heading entities are found.
func (hq *HeadingQuery) Only(ctx context.Context) (*Heading, error) {
	nodes, err := hq.Limit(2).All(setContextOp(ctx, hq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{heading.Label}
	default:
		return nil, &NotSingularError{heading.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (hq *HeadingQuery) OnlyX(ctx context.Context) *Heading {
	node, err := hq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Heading ID in the query.
// Returns a *NotSingularError when more than one Heading ID is found.
// Returns a *NotFoundError when no entities are found.
func (hq *HeadingQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = hq.Limit(2).IDs(setContextOp(ctx, hq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{heading.Label}
	default:
		err = &NotSingularError{heading.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (hq *HeadingQuery) OnlyIDX(ctx context.Context) int {
	id, err := hq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Headings.
func (hq *HeadingQuery) All(ctx context.Context) ([]*Heading, error) {
	ctx = setContextOp(ctx, hq.ctx, ent.OpQueryAll)
	if err := hq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Heading, *HeadingQuery]()
	return withInterceptors[[]*Heading](ctx, hq, qr, hq.inters)
}

// AllX is like All, but panics if an error occurs.
func (hq *HeadingQuery) AllX(ctx context.Context) []*Heading {
	nodes, err := hq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Heading IDs.
func (hq *HeadingQuery) IDs(ctx context.Context) (ids []int, err error) {
	if hq.ctx.Unique == nil && hq.path != nil {
		hq.Unique(true)
	}
	ctx = setContextOp(ctx, hq.ctx, ent.OpQueryIDs)
	if err = hq.Select(heading.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (hq *HeadingQuery) IDsX(ctx context.Context) []int {
	ids, err := hq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (hq *HeadingQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, hq.ctx, ent.OpQueryCount)
	if err := hq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, hq, querierCount[*HeadingQuery](), hq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (hq *HeadingQuery) CountX(ctx context.Context) int {
	count, err := hq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (hq *HeadingQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, hq.ctx, ent.OpQueryExist)
	switch _, err := hq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (hq *HeadingQuery) ExistX(ctx context.Context) bool {
	exist, err := hq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the HeadingQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (hq *HeadingQuery) Clone() *HeadingQuery {
	if hq == nil {
		return nil
	}
	return &HeadingQuery{
		config:             hq.config,
		ctx:                hq.ctx.Clone(),
		order:              append([]heading.OrderOption{}, hq.order...),
		inters:             append([]Interceptor{}, hq.inters...),
		predicates:         append([]predicate.Heading{}, hq.predicates...),
		withVarsity:        hq.withVarsity.Clone(),
		withApplications:   hq.withApplications.Clone(),
		withCalculations:   hq.withCalculations.Clone(),
		withDrainedResults: hq.withDrainedResults.Clone(),
		// clone intermediate query.
		sql:  hq.sql.Clone(),
		path: hq.path,
	}
}

// WithVarsity tells the query-builder to eager-load the nodes that are connected to
// the "varsity" edge. The optional arguments are used to configure the query builder of the edge.
func (hq *HeadingQuery) WithVarsity(opts ...func(*VarsityQuery)) *HeadingQuery {
	query := (&VarsityClient{config: hq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	hq.withVarsity = query
	return hq
}

// WithApplications tells the query-builder to eager-load the nodes that are connected to
// the "applications" edge. The optional arguments are used to configure the query builder of the edge.
func (hq *HeadingQuery) WithApplications(opts ...func(*ApplicationQuery)) *HeadingQuery {
	query := (&ApplicationClient{config: hq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	hq.withApplications = query
	return hq
}

// WithCalculations tells the query-builder to eager-load the nodes that are connected to
// the "calculations" edge. The optional arguments are used to configure the query builder of the edge.
func (hq *HeadingQuery) WithCalculations(opts ...func(*CalculationQuery)) *HeadingQuery {
	query := (&CalculationClient{config: hq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	hq.withCalculations = query
	return hq
}

// WithDrainedResults tells the query-builder to eager-load the nodes that are connected to
// the "drained_results" edge. The optional arguments are used to configure the query builder of the edge.
func (hq *HeadingQuery) WithDrainedResults(opts ...func(*DrainedResultQuery)) *HeadingQuery {
	query := (&DrainedResultClient{config: hq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	hq.withDrainedResults = query
	return hq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		RegularCapacity int `json:"regular_capacity,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Heading.Query().
//		GroupBy(heading.FieldRegularCapacity).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (hq *HeadingQuery) GroupBy(field string, fields ...string) *HeadingGroupBy {
	hq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &HeadingGroupBy{build: hq}
	grbuild.flds = &hq.ctx.Fields
	grbuild.label = heading.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		RegularCapacity int `json:"regular_capacity,omitempty"`
//	}
//
//	client.Heading.Query().
//		Select(heading.FieldRegularCapacity).
//		Scan(ctx, &v)
func (hq *HeadingQuery) Select(fields ...string) *HeadingSelect {
	hq.ctx.Fields = append(hq.ctx.Fields, fields...)
	sbuild := &HeadingSelect{HeadingQuery: hq}
	sbuild.label = heading.Label
	sbuild.flds, sbuild.scan = &hq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a HeadingSelect configured with the given aggregations.
func (hq *HeadingQuery) Aggregate(fns ...AggregateFunc) *HeadingSelect {
	return hq.Select().Aggregate(fns...)
}

func (hq *HeadingQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range hq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, hq); err != nil {
				return err
			}
		}
	}
	for _, f := range hq.ctx.Fields {
		if !heading.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if hq.path != nil {
		prev, err := hq.path(ctx)
		if err != nil {
			return err
		}
		hq.sql = prev
	}
	return nil
}

func (hq *HeadingQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Heading, error) {
	var (
		nodes       = []*Heading{}
		withFKs     = hq.withFKs
		_spec       = hq.querySpec()
		loadedTypes = [4]bool{
			hq.withVarsity != nil,
			hq.withApplications != nil,
			hq.withCalculations != nil,
			hq.withDrainedResults != nil,
		}
	)
	if hq.withVarsity != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, heading.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Heading).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Heading{config: hq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, hq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := hq.withVarsity; query != nil {
		if err := hq.loadVarsity(ctx, query, nodes, nil,
			func(n *Heading, e *Varsity) { n.Edges.Varsity = e }); err != nil {
			return nil, err
		}
	}
	if query := hq.withApplications; query != nil {
		if err := hq.loadApplications(ctx, query, nodes,
			func(n *Heading) { n.Edges.Applications = []*Application{} },
			func(n *Heading, e *Application) { n.Edges.Applications = append(n.Edges.Applications, e) }); err != nil {
			return nil, err
		}
	}
	if query := hq.withCalculations; query != nil {
		if err := hq.loadCalculations(ctx, query, nodes,
			func(n *Heading) { n.Edges.Calculations = []*Calculation{} },
			func(n *Heading, e *Calculation) { n.Edges.Calculations = append(n.Edges.Calculations, e) }); err != nil {
			return nil, err
		}
	}
	if query := hq.withDrainedResults; query != nil {
		if err := hq.loadDrainedResults(ctx, query, nodes,
			func(n *Heading) { n.Edges.DrainedResults = []*DrainedResult{} },
			func(n *Heading, e *DrainedResult) { n.Edges.DrainedResults = append(n.Edges.DrainedResults, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (hq *HeadingQuery) loadVarsity(ctx context.Context, query *VarsityQuery, nodes []*Heading, init func(*Heading), assign func(*Heading, *Varsity)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Heading)
	for i := range nodes {
		if nodes[i].varsity_headings == nil {
			continue
		}
		fk := *nodes[i].varsity_headings
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(varsity.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "varsity_headings" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (hq *HeadingQuery) loadApplications(ctx context.Context, query *ApplicationQuery, nodes []*Heading, init func(*Heading), assign func(*Heading, *Application)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Heading)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Application(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(heading.ApplicationsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.heading_applications
		if fk == nil {
			return fmt.Errorf(`foreign-key "heading_applications" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "heading_applications" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (hq *HeadingQuery) loadCalculations(ctx context.Context, query *CalculationQuery, nodes []*Heading, init func(*Heading), assign func(*Heading, *Calculation)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Heading)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Calculation(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(heading.CalculationsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.heading_calculations
		if fk == nil {
			return fmt.Errorf(`foreign-key "heading_calculations" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "heading_calculations" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (hq *HeadingQuery) loadDrainedResults(ctx context.Context, query *DrainedResultQuery, nodes []*Heading, init func(*Heading), assign func(*Heading, *DrainedResult)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Heading)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.DrainedResult(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(heading.DrainedResultsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.heading_drained_results
		if fk == nil {
			return fmt.Errorf(`foreign-key "heading_drained_results" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "heading_drained_results" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (hq *HeadingQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := hq.querySpec()
	_spec.Node.Columns = hq.ctx.Fields
	if len(hq.ctx.Fields) > 0 {
		_spec.Unique = hq.ctx.Unique != nil && *hq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, hq.driver, _spec)
}

func (hq *HeadingQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(heading.Table, heading.Columns, sqlgraph.NewFieldSpec(heading.FieldID, field.TypeInt))
	_spec.From = hq.sql
	if unique := hq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if hq.path != nil {
		_spec.Unique = true
	}
	if fields := hq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, heading.FieldID)
		for i := range fields {
			if fields[i] != heading.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := hq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := hq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := hq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := hq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (hq *HeadingQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(hq.driver.Dialect())
	t1 := builder.Table(heading.Table)
	columns := hq.ctx.Fields
	if len(columns) == 0 {
		columns = heading.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if hq.sql != nil {
		selector = hq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if hq.ctx.Unique != nil && *hq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range hq.predicates {
		p(selector)
	}
	for _, p := range hq.order {
		p(selector)
	}
	if offset := hq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := hq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// HeadingGroupBy is the group-by builder for Heading entities.
type HeadingGroupBy struct {
	selector
	build *HeadingQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (hgb *HeadingGroupBy) Aggregate(fns ...AggregateFunc) *HeadingGroupBy {
	hgb.fns = append(hgb.fns, fns...)
	return hgb
}

// Scan applies the selector query and scans the result into the given value.
func (hgb *HeadingGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, hgb.build.ctx, ent.OpQueryGroupBy)
	if err := hgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*HeadingQuery, *HeadingGroupBy](ctx, hgb.build, hgb, hgb.build.inters, v)
}

func (hgb *HeadingGroupBy) sqlScan(ctx context.Context, root *HeadingQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(hgb.fns))
	for _, fn := range hgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*hgb.flds)+len(hgb.fns))
		for _, f := range *hgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*hgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := hgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// HeadingSelect is the builder for selecting fields of Heading entities.
type HeadingSelect struct {
	*HeadingQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (hs *HeadingSelect) Aggregate(fns ...AggregateFunc) *HeadingSelect {
	hs.fns = append(hs.fns, fns...)
	return hs
}

// Scan applies the selector query and scans the result into the given value.
func (hs *HeadingSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, hs.ctx, ent.OpQuerySelect)
	if err := hs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*HeadingQuery, *HeadingSelect](ctx, hs.HeadingQuery, hs, hs.inters, v)
}

func (hs *HeadingSelect) sqlScan(ctx context.Context, root *HeadingQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(hs.fns))
	for _, fn := range hs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*hs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := hs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
