// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/trueegorletov/analabit/core/ent/run"
)

// Run is the model entity for the Run schema.
type Run struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// TriggeredAt holds the value of the "triggered_at" field.
	TriggeredAt time.Time `json:"triggered_at,omitempty"`
	// PayloadMeta holds the value of the "payload_meta" field.
	PayloadMeta map[string]interface{} `json:"payload_meta,omitempty"`
	// Finished holds the value of the "finished" field.
	Finished     bool `json:"finished,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Run) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case run.FieldPayloadMeta:
			values[i] = new([]byte)
		case run.FieldFinished:
			values[i] = new(sql.NullBool)
		case run.FieldID:
			values[i] = new(sql.NullInt64)
		case run.FieldTriggeredAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Run fields.
func (r *Run) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case run.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			r.ID = int(value.Int64)
		case run.FieldTriggeredAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field triggered_at", values[i])
			} else if value.Valid {
				r.TriggeredAt = value.Time
			}
		case run.FieldPayloadMeta:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field payload_meta", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &r.PayloadMeta); err != nil {
					return fmt.Errorf("unmarshal field payload_meta: %w", err)
				}
			}
		case run.FieldFinished:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field finished", values[i])
			} else if value.Valid {
				r.Finished = value.Bool
			}
		default:
			r.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Run.
// This includes values selected through modifiers, order, etc.
func (r *Run) Value(name string) (ent.Value, error) {
	return r.selectValues.Get(name)
}

// Update returns a builder for updating this Run.
// Note that you need to call Run.Unwrap() before calling this method if this Run
// was returned from a transaction, and the transaction was committed or rolled back.
func (r *Run) Update() *RunUpdateOne {
	return NewRunClient(r.config).UpdateOne(r)
}

// Unwrap unwraps the Run entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (r *Run) Unwrap() *Run {
	_tx, ok := r.config.driver.(*txDriver)
	if !ok {
		panic("ent: Run is not a transactional entity")
	}
	r.config.driver = _tx.drv
	return r
}

// String implements the fmt.Stringer.
func (r *Run) String() string {
	var builder strings.Builder
	builder.WriteString("Run(")
	builder.WriteString(fmt.Sprintf("id=%v, ", r.ID))
	builder.WriteString("triggered_at=")
	builder.WriteString(r.TriggeredAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("payload_meta=")
	builder.WriteString(fmt.Sprintf("%v", r.PayloadMeta))
	builder.WriteString(", ")
	builder.WriteString("finished=")
	builder.WriteString(fmt.Sprintf("%v", r.Finished))
	builder.WriteByte(')')
	return builder.String()
}

// Runs is a parsable slice of Run.
type Runs []*Run
