// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/trueegorletov/analabit/core/ent/predicate"
	"github.com/trueegorletov/analabit/core/ent/run"
)

// RunUpdate is the builder for updating Run entities.
type RunUpdate struct {
	config
	hooks    []Hook
	mutation *RunMutation
}

// Where appends a list predicates to the RunUpdate builder.
func (ru *RunUpdate) Where(ps ...predicate.Run) *RunUpdate {
	ru.mutation.Where(ps...)
	return ru
}

// SetTriggeredAt sets the "triggered_at" field.
func (ru *RunUpdate) SetTriggeredAt(t time.Time) *RunUpdate {
	ru.mutation.SetTriggeredAt(t)
	return ru
}

// SetNillableTriggeredAt sets the "triggered_at" field if the given value is not nil.
func (ru *RunUpdate) SetNillableTriggeredAt(t *time.Time) *RunUpdate {
	if t != nil {
		ru.SetTriggeredAt(*t)
	}
	return ru
}

// SetPayloadMeta sets the "payload_meta" field.
func (ru *RunUpdate) SetPayloadMeta(m map[string]interface{}) *RunUpdate {
	ru.mutation.SetPayloadMeta(m)
	return ru
}

// ClearPayloadMeta clears the value of the "payload_meta" field.
func (ru *RunUpdate) ClearPayloadMeta() *RunUpdate {
	ru.mutation.ClearPayloadMeta()
	return ru
}

// SetFinished sets the "finished" field.
func (ru *RunUpdate) SetFinished(b bool) *RunUpdate {
	ru.mutation.SetFinished(b)
	return ru
}

// SetNillableFinished sets the "finished" field if the given value is not nil.
func (ru *RunUpdate) SetNillableFinished(b *bool) *RunUpdate {
	if b != nil {
		ru.SetFinished(*b)
	}
	return ru
}

// Mutation returns the RunMutation object of the builder.
func (ru *RunUpdate) Mutation() *RunMutation {
	return ru.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ru *RunUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, ru.sqlSave, ru.mutation, ru.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ru *RunUpdate) SaveX(ctx context.Context) int {
	affected, err := ru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ru *RunUpdate) Exec(ctx context.Context) error {
	_, err := ru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ru *RunUpdate) ExecX(ctx context.Context) {
	if err := ru.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ru *RunUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(run.Table, run.Columns, sqlgraph.NewFieldSpec(run.FieldID, field.TypeInt))
	if ps := ru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ru.mutation.TriggeredAt(); ok {
		_spec.SetField(run.FieldTriggeredAt, field.TypeTime, value)
	}
	if value, ok := ru.mutation.PayloadMeta(); ok {
		_spec.SetField(run.FieldPayloadMeta, field.TypeJSON, value)
	}
	if ru.mutation.PayloadMetaCleared() {
		_spec.ClearField(run.FieldPayloadMeta, field.TypeJSON)
	}
	if value, ok := ru.mutation.Finished(); ok {
		_spec.SetField(run.FieldFinished, field.TypeBool, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{run.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ru.mutation.done = true
	return n, nil
}

// RunUpdateOne is the builder for updating a single Run entity.
type RunUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RunMutation
}

// SetTriggeredAt sets the "triggered_at" field.
func (ruo *RunUpdateOne) SetTriggeredAt(t time.Time) *RunUpdateOne {
	ruo.mutation.SetTriggeredAt(t)
	return ruo
}

// SetNillableTriggeredAt sets the "triggered_at" field if the given value is not nil.
func (ruo *RunUpdateOne) SetNillableTriggeredAt(t *time.Time) *RunUpdateOne {
	if t != nil {
		ruo.SetTriggeredAt(*t)
	}
	return ruo
}

// SetPayloadMeta sets the "payload_meta" field.
func (ruo *RunUpdateOne) SetPayloadMeta(m map[string]interface{}) *RunUpdateOne {
	ruo.mutation.SetPayloadMeta(m)
	return ruo
}

// ClearPayloadMeta clears the value of the "payload_meta" field.
func (ruo *RunUpdateOne) ClearPayloadMeta() *RunUpdateOne {
	ruo.mutation.ClearPayloadMeta()
	return ruo
}

// SetFinished sets the "finished" field.
func (ruo *RunUpdateOne) SetFinished(b bool) *RunUpdateOne {
	ruo.mutation.SetFinished(b)
	return ruo
}

// SetNillableFinished sets the "finished" field if the given value is not nil.
func (ruo *RunUpdateOne) SetNillableFinished(b *bool) *RunUpdateOne {
	if b != nil {
		ruo.SetFinished(*b)
	}
	return ruo
}

// Mutation returns the RunMutation object of the builder.
func (ruo *RunUpdateOne) Mutation() *RunMutation {
	return ruo.mutation
}

// Where appends a list predicates to the RunUpdate builder.
func (ruo *RunUpdateOne) Where(ps ...predicate.Run) *RunUpdateOne {
	ruo.mutation.Where(ps...)
	return ruo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ruo *RunUpdateOne) Select(field string, fields ...string) *RunUpdateOne {
	ruo.fields = append([]string{field}, fields...)
	return ruo
}

// Save executes the query and returns the updated Run entity.
func (ruo *RunUpdateOne) Save(ctx context.Context) (*Run, error) {
	return withHooks(ctx, ruo.sqlSave, ruo.mutation, ruo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ruo *RunUpdateOne) SaveX(ctx context.Context) *Run {
	node, err := ruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ruo *RunUpdateOne) Exec(ctx context.Context) error {
	_, err := ruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ruo *RunUpdateOne) ExecX(ctx context.Context) {
	if err := ruo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ruo *RunUpdateOne) sqlSave(ctx context.Context) (_node *Run, err error) {
	_spec := sqlgraph.NewUpdateSpec(run.Table, run.Columns, sqlgraph.NewFieldSpec(run.FieldID, field.TypeInt))
	id, ok := ruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Run.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ruo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, run.FieldID)
		for _, f := range fields {
			if !run.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != run.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ruo.mutation.TriggeredAt(); ok {
		_spec.SetField(run.FieldTriggeredAt, field.TypeTime, value)
	}
	if value, ok := ruo.mutation.PayloadMeta(); ok {
		_spec.SetField(run.FieldPayloadMeta, field.TypeJSON, value)
	}
	if ruo.mutation.PayloadMetaCleared() {
		_spec.ClearField(run.FieldPayloadMeta, field.TypeJSON)
	}
	if value, ok := ruo.mutation.Finished(); ok {
		_spec.SetField(run.FieldFinished, field.TypeBool, value)
	}
	_node = &Run{config: ruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{run.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ruo.mutation.done = true
	return _node, nil
}
