// Code generated by ent, DO NOT EDIT.

package ent

import (
	"analabit/core/ent/predicate"
	"analabit/core/ent/varsity"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// VarsityDelete is the builder for deleting a Varsity entity.
type VarsityDelete struct {
	config
	hooks    []Hook
	mutation *VarsityMutation
}

// Where appends a list predicates to the VarsityDelete builder.
func (vd *VarsityDelete) Where(ps ...predicate.Varsity) *VarsityDelete {
	vd.mutation.Where(ps...)
	return vd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (vd *VarsityDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, vd.sqlExec, vd.mutation, vd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (vd *VarsityDelete) ExecX(ctx context.Context) int {
	n, err := vd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (vd *VarsityDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(varsity.Table, sqlgraph.NewFieldSpec(varsity.FieldID, field.TypeInt))
	if ps := vd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, vd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	vd.mutation.done = true
	return affected, err
}

// VarsityDeleteOne is the builder for deleting a single Varsity entity.
type VarsityDeleteOne struct {
	vd *VarsityDelete
}

// Where appends a list predicates to the VarsityDelete builder.
func (vdo *VarsityDeleteOne) Where(ps ...predicate.Varsity) *VarsityDeleteOne {
	vdo.vd.mutation.Where(ps...)
	return vdo
}

// Exec executes the deletion query.
func (vdo *VarsityDeleteOne) Exec(ctx context.Context) error {
	n, err := vdo.vd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{varsity.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (vdo *VarsityDeleteOne) ExecX(ctx context.Context) {
	if err := vdo.Exec(ctx); err != nil {
		panic(err)
	}
}
