# Configuration file for the API service

[server]
port = "3000"

[database]
host = "localhost"
port = 5432
user = "analabit"
dbname = "analabit"
password = "password"
sslmode = "disable"

[logging]
file = "api.log"

