// Code generated by ent, DO NOT EDIT.

package application

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the application type in the database.
	Label = "application"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldStudentID holds the string denoting the student_id field in the database.
	FieldStudentID = "student_id"
	// FieldPriority holds the string denoting the priority field in the database.
	FieldPriority = "priority"
	// FieldCompetitionType holds the string denoting the competition_type field in the database.
	FieldCompetitionType = "competition_type"
	// FieldRatingPlace holds the string denoting the rating_place field in the database.
	FieldRatingPlace = "rating_place"
	// FieldScore holds the string denoting the score field in the database.
	FieldScore = "score"
	// FieldRunID holds the string denoting the run_id field in the database.
	FieldRunID = "run_id"
	// FieldOriginalSubmitted holds the string denoting the original_submitted field in the database.
	FieldOriginalSubmitted = "original_submitted"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldMsuInternalID holds the string denoting the msu_internal_id field in the database.
	FieldMsuInternalID = "msu_internal_id"
	// EdgeHeading holds the string denoting the heading edge name in mutations.
	EdgeHeading = "heading"
	// EdgeRun holds the string denoting the run edge name in mutations.
	EdgeRun = "run"
	// Table holds the table name of the application in the database.
	Table = "applications"
	// HeadingTable is the table that holds the heading relation/edge.
	HeadingTable = "applications"
	// HeadingInverseTable is the table name for the Heading entity.
	// It exists in this package in order to avoid circular dependency with the "heading" package.
	HeadingInverseTable = "headings"
	// HeadingColumn is the table column denoting the heading relation/edge.
	HeadingColumn = "heading_applications"
	// RunTable is the table that holds the run relation/edge.
	RunTable = "applications"
	// RunInverseTable is the table name for the Run entity.
	// It exists in this package in order to avoid circular dependency with the "run" package.
	RunInverseTable = "runs"
	// RunColumn is the table column denoting the run relation/edge.
	RunColumn = "run_id"
)

// Columns holds all SQL columns for application fields.
var Columns = []string{
	FieldID,
	FieldStudentID,
	FieldPriority,
	FieldCompetitionType,
	FieldRatingPlace,
	FieldScore,
	FieldRunID,
	FieldOriginalSubmitted,
	FieldUpdatedAt,
	FieldMsuInternalID,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "applications"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"heading_applications",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultOriginalSubmitted holds the default value on creation for the "original_submitted" field.
	DefaultOriginalSubmitted bool
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the Application queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByStudentID orders the results by the student_id field.
func ByStudentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStudentID, opts...).ToFunc()
}

// ByPriority orders the results by the priority field.
func ByPriority(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriority, opts...).ToFunc()
}

// ByCompetitionType orders the results by the competition_type field.
func ByCompetitionType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompetitionType, opts...).ToFunc()
}

// ByRatingPlace orders the results by the rating_place field.
func ByRatingPlace(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRatingPlace, opts...).ToFunc()
}

// ByScore orders the results by the score field.
func ByScore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScore, opts...).ToFunc()
}

// ByRunID orders the results by the run_id field.
func ByRunID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRunID, opts...).ToFunc()
}

// ByOriginalSubmitted orders the results by the original_submitted field.
func ByOriginalSubmitted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOriginalSubmitted, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByMsuInternalID orders the results by the msu_internal_id field.
func ByMsuInternalID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMsuInternalID, opts...).ToFunc()
}

// ByHeadingField orders the results by heading field.
func ByHeadingField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newHeadingStep(), sql.OrderByField(field, opts...))
	}
}

// ByRunField orders the results by run field.
func ByRunField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRunStep(), sql.OrderByField(field, opts...))
	}
}
func newHeadingStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(HeadingInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, HeadingTable, HeadingColumn),
	)
}
func newRunStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RunInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, RunTable, RunColumn),
	)
}
