// Code generated by ent, DO NOT EDIT.

package application

import (
	"analabit/core"
	"analabit/core/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Application {
	return predicate.Application(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Application {
	return predicate.Application(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Application {
	return predicate.Application(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Application {
	return predicate.Application(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Application {
	return predicate.Application(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Application {
	return predicate.Application(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Application {
	return predicate.Application(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Application {
	return predicate.Application(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Application {
	return predicate.Application(sql.FieldLTE(FieldID, id))
}

// StudentID applies equality check predicate on the "student_id" field. It's identical to StudentIDEQ.
func StudentID(v string) predicate.Application {
	return predicate.Application(sql.FieldEQ(FieldStudentID, v))
}

// Priority applies equality check predicate on the "priority" field. It's identical to PriorityEQ.
func Priority(v int) predicate.Application {
	return predicate.Application(sql.FieldEQ(FieldPriority, v))
}

// CompetitionType applies equality check predicate on the "competition_type" field. It's identical to CompetitionTypeEQ.
func CompetitionType(v core.Competition) predicate.Application {
	vc := int(v)
	return predicate.Application(sql.FieldEQ(FieldCompetitionType, vc))
}

// RatingPlace applies equality check predicate on the "rating_place" field. It's identical to RatingPlaceEQ.
func RatingPlace(v int) predicate.Application {
	return predicate.Application(sql.FieldEQ(FieldRatingPlace, v))
}

// Score applies equality check predicate on the "score" field. It's identical to ScoreEQ.
func Score(v int) predicate.Application {
	return predicate.Application(sql.FieldEQ(FieldScore, v))
}

// RunID applies equality check predicate on the "run_id" field. It's identical to RunIDEQ.
func RunID(v int) predicate.Application {
	return predicate.Application(sql.FieldEQ(FieldRunID, v))
}

// OriginalSubmitted applies equality check predicate on the "original_submitted" field. It's identical to OriginalSubmittedEQ.
func OriginalSubmitted(v bool) predicate.Application {
	return predicate.Application(sql.FieldEQ(FieldOriginalSubmitted, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Application {
	return predicate.Application(sql.FieldEQ(FieldUpdatedAt, v))
}

// StudentIDEQ applies the EQ predicate on the "student_id" field.
func StudentIDEQ(v string) predicate.Application {
	return predicate.Application(sql.FieldEQ(FieldStudentID, v))
}

// StudentIDNEQ applies the NEQ predicate on the "student_id" field.
func StudentIDNEQ(v string) predicate.Application {
	return predicate.Application(sql.FieldNEQ(FieldStudentID, v))
}

// StudentIDIn applies the In predicate on the "student_id" field.
func StudentIDIn(vs ...string) predicate.Application {
	return predicate.Application(sql.FieldIn(FieldStudentID, vs...))
}

// StudentIDNotIn applies the NotIn predicate on the "student_id" field.
func StudentIDNotIn(vs ...string) predicate.Application {
	return predicate.Application(sql.FieldNotIn(FieldStudentID, vs...))
}

// StudentIDGT applies the GT predicate on the "student_id" field.
func StudentIDGT(v string) predicate.Application {
	return predicate.Application(sql.FieldGT(FieldStudentID, v))
}

// StudentIDGTE applies the GTE predicate on the "student_id" field.
func StudentIDGTE(v string) predicate.Application {
	return predicate.Application(sql.FieldGTE(FieldStudentID, v))
}

// StudentIDLT applies the LT predicate on the "student_id" field.
func StudentIDLT(v string) predicate.Application {
	return predicate.Application(sql.FieldLT(FieldStudentID, v))
}

// StudentIDLTE applies the LTE predicate on the "student_id" field.
func StudentIDLTE(v string) predicate.Application {
	return predicate.Application(sql.FieldLTE(FieldStudentID, v))
}

// StudentIDContains applies the Contains predicate on the "student_id" field.
func StudentIDContains(v string) predicate.Application {
	return predicate.Application(sql.FieldContains(FieldStudentID, v))
}

// StudentIDHasPrefix applies the HasPrefix predicate on the "student_id" field.
func StudentIDHasPrefix(v string) predicate.Application {
	return predicate.Application(sql.FieldHasPrefix(FieldStudentID, v))
}

// StudentIDHasSuffix applies the HasSuffix predicate on the "student_id" field.
func StudentIDHasSuffix(v string) predicate.Application {
	return predicate.Application(sql.FieldHasSuffix(FieldStudentID, v))
}

// StudentIDEqualFold applies the EqualFold predicate on the "student_id" field.
func StudentIDEqualFold(v string) predicate.Application {
	return predicate.Application(sql.FieldEqualFold(FieldStudentID, v))
}

// StudentIDContainsFold applies the ContainsFold predicate on the "student_id" field.
func StudentIDContainsFold(v string) predicate.Application {
	return predicate.Application(sql.FieldContainsFold(FieldStudentID, v))
}

// PriorityEQ applies the EQ predicate on the "priority" field.
func PriorityEQ(v int) predicate.Application {
	return predicate.Application(sql.FieldEQ(FieldPriority, v))
}

// PriorityNEQ applies the NEQ predicate on the "priority" field.
func PriorityNEQ(v int) predicate.Application {
	return predicate.Application(sql.FieldNEQ(FieldPriority, v))
}

// PriorityIn applies the In predicate on the "priority" field.
func PriorityIn(vs ...int) predicate.Application {
	return predicate.Application(sql.FieldIn(FieldPriority, vs...))
}

// PriorityNotIn applies the NotIn predicate on the "priority" field.
func PriorityNotIn(vs ...int) predicate.Application {
	return predicate.Application(sql.FieldNotIn(FieldPriority, vs...))
}

// PriorityGT applies the GT predicate on the "priority" field.
func PriorityGT(v int) predicate.Application {
	return predicate.Application(sql.FieldGT(FieldPriority, v))
}

// PriorityGTE applies the GTE predicate on the "priority" field.
func PriorityGTE(v int) predicate.Application {
	return predicate.Application(sql.FieldGTE(FieldPriority, v))
}

// PriorityLT applies the LT predicate on the "priority" field.
func PriorityLT(v int) predicate.Application {
	return predicate.Application(sql.FieldLT(FieldPriority, v))
}

// PriorityLTE applies the LTE predicate on the "priority" field.
func PriorityLTE(v int) predicate.Application {
	return predicate.Application(sql.FieldLTE(FieldPriority, v))
}

// CompetitionTypeEQ applies the EQ predicate on the "competition_type" field.
func CompetitionTypeEQ(v core.Competition) predicate.Application {
	vc := int(v)
	return predicate.Application(sql.FieldEQ(FieldCompetitionType, vc))
}

// CompetitionTypeNEQ applies the NEQ predicate on the "competition_type" field.
func CompetitionTypeNEQ(v core.Competition) predicate.Application {
	vc := int(v)
	return predicate.Application(sql.FieldNEQ(FieldCompetitionType, vc))
}

// CompetitionTypeIn applies the In predicate on the "competition_type" field.
func CompetitionTypeIn(vs ...core.Competition) predicate.Application {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = int(vs[i])
	}
	return predicate.Application(sql.FieldIn(FieldCompetitionType, v...))
}

// CompetitionTypeNotIn applies the NotIn predicate on the "competition_type" field.
func CompetitionTypeNotIn(vs ...core.Competition) predicate.Application {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = int(vs[i])
	}
	return predicate.Application(sql.FieldNotIn(FieldCompetitionType, v...))
}

// CompetitionTypeGT applies the GT predicate on the "competition_type" field.
func CompetitionTypeGT(v core.Competition) predicate.Application {
	vc := int(v)
	return predicate.Application(sql.FieldGT(FieldCompetitionType, vc))
}

// CompetitionTypeGTE applies the GTE predicate on the "competition_type" field.
func CompetitionTypeGTE(v core.Competition) predicate.Application {
	vc := int(v)
	return predicate.Application(sql.FieldGTE(FieldCompetitionType, vc))
}

// CompetitionTypeLT applies the LT predicate on the "competition_type" field.
func CompetitionTypeLT(v core.Competition) predicate.Application {
	vc := int(v)
	return predicate.Application(sql.FieldLT(FieldCompetitionType, vc))
}

// CompetitionTypeLTE applies the LTE predicate on the "competition_type" field.
func CompetitionTypeLTE(v core.Competition) predicate.Application {
	vc := int(v)
	return predicate.Application(sql.FieldLTE(FieldCompetitionType, vc))
}

// RatingPlaceEQ applies the EQ predicate on the "rating_place" field.
func RatingPlaceEQ(v int) predicate.Application {
	return predicate.Application(sql.FieldEQ(FieldRatingPlace, v))
}

// RatingPlaceNEQ applies the NEQ predicate on the "rating_place" field.
func RatingPlaceNEQ(v int) predicate.Application {
	return predicate.Application(sql.FieldNEQ(FieldRatingPlace, v))
}

// RatingPlaceIn applies the In predicate on the "rating_place" field.
func RatingPlaceIn(vs ...int) predicate.Application {
	return predicate.Application(sql.FieldIn(FieldRatingPlace, vs...))
}

// RatingPlaceNotIn applies the NotIn predicate on the "rating_place" field.
func RatingPlaceNotIn(vs ...int) predicate.Application {
	return predicate.Application(sql.FieldNotIn(FieldRatingPlace, vs...))
}

// RatingPlaceGT applies the GT predicate on the "rating_place" field.
func RatingPlaceGT(v int) predicate.Application {
	return predicate.Application(sql.FieldGT(FieldRatingPlace, v))
}

// RatingPlaceGTE applies the GTE predicate on the "rating_place" field.
func RatingPlaceGTE(v int) predicate.Application {
	return predicate.Application(sql.FieldGTE(FieldRatingPlace, v))
}

// RatingPlaceLT applies the LT predicate on the "rating_place" field.
func RatingPlaceLT(v int) predicate.Application {
	return predicate.Application(sql.FieldLT(FieldRatingPlace, v))
}

// RatingPlaceLTE applies the LTE predicate on the "rating_place" field.
func RatingPlaceLTE(v int) predicate.Application {
	return predicate.Application(sql.FieldLTE(FieldRatingPlace, v))
}

// ScoreEQ applies the EQ predicate on the "score" field.
func ScoreEQ(v int) predicate.Application {
	return predicate.Application(sql.FieldEQ(FieldScore, v))
}

// ScoreNEQ applies the NEQ predicate on the "score" field.
func ScoreNEQ(v int) predicate.Application {
	return predicate.Application(sql.FieldNEQ(FieldScore, v))
}

// ScoreIn applies the In predicate on the "score" field.
func ScoreIn(vs ...int) predicate.Application {
	return predicate.Application(sql.FieldIn(FieldScore, vs...))
}

// ScoreNotIn applies the NotIn predicate on the "score" field.
func ScoreNotIn(vs ...int) predicate.Application {
	return predicate.Application(sql.FieldNotIn(FieldScore, vs...))
}

// ScoreGT applies the GT predicate on the "score" field.
func ScoreGT(v int) predicate.Application {
	return predicate.Application(sql.FieldGT(FieldScore, v))
}

// ScoreGTE applies the GTE predicate on the "score" field.
func ScoreGTE(v int) predicate.Application {
	return predicate.Application(sql.FieldGTE(FieldScore, v))
}

// ScoreLT applies the LT predicate on the "score" field.
func ScoreLT(v int) predicate.Application {
	return predicate.Application(sql.FieldLT(FieldScore, v))
}

// ScoreLTE applies the LTE predicate on the "score" field.
func ScoreLTE(v int) predicate.Application {
	return predicate.Application(sql.FieldLTE(FieldScore, v))
}

// RunIDEQ applies the EQ predicate on the "run_id" field.
func RunIDEQ(v int) predicate.Application {
	return predicate.Application(sql.FieldEQ(FieldRunID, v))
}

// RunIDNEQ applies the NEQ predicate on the "run_id" field.
func RunIDNEQ(v int) predicate.Application {
	return predicate.Application(sql.FieldNEQ(FieldRunID, v))
}

// RunIDIn applies the In predicate on the "run_id" field.
func RunIDIn(vs ...int) predicate.Application {
	return predicate.Application(sql.FieldIn(FieldRunID, vs...))
}

// RunIDNotIn applies the NotIn predicate on the "run_id" field.
func RunIDNotIn(vs ...int) predicate.Application {
	return predicate.Application(sql.FieldNotIn(FieldRunID, vs...))
}

// OriginalSubmittedEQ applies the EQ predicate on the "original_submitted" field.
func OriginalSubmittedEQ(v bool) predicate.Application {
	return predicate.Application(sql.FieldEQ(FieldOriginalSubmitted, v))
}

// OriginalSubmittedNEQ applies the NEQ predicate on the "original_submitted" field.
func OriginalSubmittedNEQ(v bool) predicate.Application {
	return predicate.Application(sql.FieldNEQ(FieldOriginalSubmitted, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Application {
	return predicate.Application(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Application {
	return predicate.Application(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Application {
	return predicate.Application(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Application {
	return predicate.Application(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Application {
	return predicate.Application(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Application {
	return predicate.Application(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Application {
	return predicate.Application(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Application {
	return predicate.Application(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasHeading applies the HasEdge predicate on the "heading" edge.
func HasHeading() predicate.Application {
	return predicate.Application(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, HeadingTable, HeadingColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasHeadingWith applies the HasEdge predicate on the "heading" edge with a given conditions (other predicates).
func HasHeadingWith(preds ...predicate.Heading) predicate.Application {
	return predicate.Application(func(s *sql.Selector) {
		step := newHeadingStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRun applies the HasEdge predicate on the "run" edge.
func HasRun() predicate.Application {
	return predicate.Application(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, RunTable, RunColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRunWith applies the HasEdge predicate on the "run" edge with a given conditions (other predicates).
func HasRunWith(preds ...predicate.Run) predicate.Application {
	return predicate.Application(func(s *sql.Selector) {
		step := newRunStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Application) predicate.Application {
	return predicate.Application(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Application) predicate.Application {
	return predicate.Application(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Application) predicate.Application {
	return predicate.Application(sql.NotPredicates(p))
}
